---
zsystems:
  hosts:
    z32a:
      ansible_host: 10.1.1.2
      ansible_user: ibmuser
      ansible_port: 65522
      ansible_password: sys1
      ansible_connection: ssh
      ansible_shell_type: sh
      ansible_shell_executable: /bin/sh