---
- name: Manage Podman Containers
  hosts: localhost
  tasks:
    - name: Create and start multiple containers
      containers.podman.podman_container:
        name: "test-container-{{ item }}"
        image: docker.io/library/nginx:latest
        state: started
        ports:
          - "808{{ item }}:80"
      loop: "{{ range(1, 11) | list }}"
      register: container_results

    - name: Display container information
      debug:
        msg: "Container {{ item.container.Name }} started with ID {{ item.container.Id }}"
      loop: "{{ container_results.results }}"

    # Optional task to stop containers
    - name: Stop containers
      containers.podman.podman_container:
        name: "test-container-{{ item }}"
        state: stopped
      loop: "{{ range(1, 11) | list }}"
      when: stop_containers is defined