###############################################################################
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Example:
#  ansible-playbook -i inventory wasi_dataset_commander.yml
#  ansible-playbook -i inventory wasi_dataset_commander.yml -v
###############################################################################
---
- hosts: s0w1 
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  vars:
    adcd_ver: Z24C

  environment: "{{ environment_vars }}"

  tasks:
    - name: Ping using zos_ping
      zos_ping:
      register: zos_ping_result

    - name: Response from zos_ping
      debug:
        msg: "{{ zos_ping_result }}"

###############################################################################
# Usage:
#  Copy ISPFPROC to ISPFPRDC; replace if it already exists
###############################################################################

    - name: Copy ISPFPROC to ISPFPRDC; replace if it already exists.
      zos_copy:
        src: ADCD.{{ adcd_ver }}.PROCLIB(ISPFPROC)
        dest: USER.{{ adcd_ver }}.PROCLIB(ISPFPRDC)
        remote_src: true
      register: zos_copy_result

    - name: DEBUG(-v) Response from Copy ISPFPROC to ISPFPRDC.
      debug:
        msg: "{{ zos_copy_result }} with verbosity 1"
        verbosity: 1

###############################################################################
# Usage:
#  Insert STEPLIB DD in ISPFPRDS
###############################################################################

    - name: Insert STEPLIB DD in ISPFPRDS.
      zos_blockinfile:
        src: USER.{{ adcd_ver }}.PARMLIB(ISPFPRDC)
        marker: "/* {mark} ANSIBLE MANAGED BLOCK */"
        insertafter: "//             PARM='%ISPFCL'"
        block: |
          //STEPLIB  DD  DISP=SHR,DSN=IQI910.SIQILPA 
          //         DD  DISP=SHR,DSN=IQI910.SIQILOAD
      register: zos_blockinfile_result

    - name: DEBUG(-v) Response from Insert STEPLIB DD in ISPFPRDS.
      debug:
        msg: "{{ zos_blockinfile_result }} with verbosity 1"
        verbosity: 1

