###############################################################################
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Example:
#  ansible-playbook -i inventory backup_volumes.yml
#  ansible-playbook -i inventory backup_volumes.yml -v
###############################################################################
---
- hosts: rhel
  tasks:
    - name: Archive z25c volumes
      archive:
        path: /home/ibmsys1/volumes-z25c
        dest: "/home/ibmsys1/volumes-backup/volumes-z25c-{{ansible_date_time.date.replace('-','')}}.zip"
        format: zip

