# backup_volumes.yml
# This Ansible playbook archives the specified directory and stores the archive
# in a specified destination with a timestamp in the filename.
# Usage:
#  ansible-playbook -i <inventory> <playbook>
# Example:
#  ansible-playbook -i inventories backup_volumes.yml
#  ansible-playbook -i inventories backup_volumes.yml -v
---
- name: Backup volumes
  hosts: rhel

  # The variables for the playbook, including the source and destination directories
  # and the name of the archive to be created
  vars:
    src_dir: "/home/ibmsys1/volumes-z25c"
    dest_dir: "/home/ibmsys1/volumes-backup"
    archive_name: "volumes-z25c-{{ ansible_date_time.date.replace('-', '') }}.zip"

  tasks:
    # Check if the source directory exists
    - name: Check if source directory exists
      ansible.builtin.stat:
        path: "{{ src_dir }}"
      register: src_dir_stat

    # Create the destination directory if it does not exist
    - name: Create destination directory if it does not exist
      ansible.builtin.file:
        path: "{{ dest_dir }}"
        state: directory
        mode: '0755'

    # Archive the source directory to a zip file with a timestamp in the filename
    - name: Archive z25c volumes
      ansible.builtin.archive:
        path: "{{ src_dir }}"
        dest: "{{ dest_dir }}/{{ archive_name }}"
        format: zip
      notify: Archive created

  # The list of handlers to be executed when a task notifies them
  handlers:
    # Print a debug message when the archive is created
    - name: Debug message
      ansible.builtin.debug:
        msg: "Archive created successfully"
