# backup_z31a_volumes.yml
# This Ansible playbook archives the specified directory and stores the archive
# in a specified destination with a timestamp in the filename.
# Usage:
#  ansible-playbook -i <inventory> <playbook>
# Example:
#  ansible-playbook -i inventories backup_z31a_volumes.yml 
#  ansible-playbook -i inventories backup_z31a_volumes.yml -v 
---
- name: Backup volumes
  hosts: zPDT

  vars:
    src_dir: "/home/ibmsys1/volumes-z31a"
    dest_dir: "/home/ibmsys1/volumes-backup"
    archive_name: "volumes-z31a-{{ ansible_date_time.date.replace('-', '') }}.tar.xz"

  tasks:
    - name: Check RHEL version
      ansible.builtin.command: cat /etc/redhat-release
      register: rhel_version
      changed_when: false

    - name: Check if source directory exists
      ansible.builtin.stat:
        path: "{{ src_dir }}"
      register: src_dir_stat
      failed_when: not src_dir_stat.stat.exists

    - name: Create destination directory if it does not exist
      ansible.builtin.file:
        path: "{{ dest_dir }}"
        state: directory
        mode: '0755'

    - name: Archive z31a volumes using tar with fast xz compression
      ansible.builtin.command: >
        tar -c -I 'xz --fast' -f {{ dest_dir }}/{{ archive_name }} -C {{ src_dir }} .
      when: src_dir_stat.stat.exists
      register: tar_result
      failed_when: tar_result.rc != 0

    - name: Verify Archive
      ansible.builtin.stat:
        path: "{{ dest_dir }}/{{ archive_name }}"
      register: archive_stat
      failed_when: not archive_stat.stat.exists

  handlers:
    - name: Debug message
      ansible.builtin.debug:
        msg: "Archive created successfully. RHEL Version: {{ rhel_version.stdout }}"