# backup_z25c_volumes.yml
# This Ansible playbook installs docker ce.
# Usage:
#  ansible-playbook -i <inventory> <playbook>
# Example:
#  ansible-playbook -i inventories install_docker.yml
#  ansible-playbook -i inventories install_docker.yml -v
---
- name: Install Docker on Red Hat Linux
  hosts: p52
  become: true

  tasks:
    - name: Add Docker repository
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - Official
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        state: present

    - name: Install required packages
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
