################################################################################
# Optimizes network settings for z/PDT systems
#
# Requirements:
# - Ansible 2.9+
# - Root access
# - RHEL system
#
# Usage:
# ansible-playbook -i inventories/inventory.yml optimize_zpdt_network.yml --ask-become-pass
# Optional: -e "network_interface=enp86s0 make_persistent=true"
################################################################################

---
- name: nuc Network Optimization
  hosts: nuc
  become: yes
  gather_facts: yes

  vars:
    network_interface: enp86s0
    offload_options:
      - rx
      - tso
      - gso
      - gro
      - lro
    make_persistent: false

  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.package:
        name:
          - ethtool
          - tuned
        state: present

    - name: Verify network interface exists
      ansible.builtin.command: "ip link show {{ network_interface }}"
      register: interface_check
      failed_when: interface_check.rc != 0
      changed_when: false

    - name: Disable network offload options
      ansible.builtin.command: "ethtool -K {{ network_interface }} {{ item }} off"
      loop: "{{ offload_options }}"
      register: disable_result
      changed_when: "'Actual changes' in disable_result.stderr"
      failed_when:
        - disable_result.rc != 0
        - "'Cannot change' not in disable_result.stderr"

    - name: Increase NIC ring buffer sizes
      ansible.builtin.command: "ethtool -G {{ network_interface }} rx 4096 tx 4096"
      register: ring_buffer_result
      changed_when: ring_buffer_result.rc == 0
      failed_when: ring_buffer_result.rc != 0

    - name: Set RX interrupt coalescing (IGC-compatible)
      ansible.builtin.command: "ethtool -C {{ network_interface }} rx-usecs 32"
      register: coalesce_result
      changed_when: coalesce_result.rc == 0
      failed_when: coalesce_result.rc != 0

    - name: Tune TCP socket buffer sizes
      ansible.builtin.sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      loop:
        - { key: 'net.core.rmem_max', value: '16777216' }
        - { key: 'net.core.wmem_max', value: '16777216' }
        - { key: 'net.ipv4.tcp_rmem', value: '4096 87380 16777216' }
        - { key: 'net.ipv4.tcp_wmem', value: '4096 65536 16777216' }
        - { key: 'net.ipv4.tcp_window_scaling', value: '1' }

    - name: Apply tuned profile for network throughput
      ansible.builtin.command: "tuned-adm profile network-throughput"

    - name: Make changes persistent
      block:
        - name: Create network scripts directory
          ansible.builtin.file:
            path: /etc/sysconfig/network-scripts
            state: directory
            mode: '0755'

        - name: Create or update ifup-local script
          ansible.builtin.template:
            src: ifup-local.j2
            dest: /etc/sysconfig/network-scripts/ifup-local
            mode: '0755'
          vars:
            interface: "{{ network_interface }}"
            options: "{{ offload_options }}"

        - name: Ensure ifup-local is executed
          ansible.builtin.lineinfile:
            path: /etc/sysconfig/network-scripts/ifup
            line: "if [ -x /etc/sysconfig/network-scripts/ifup-local ]; then /etc/sysconfig/network-scripts/ifup-local ${DEVICE}; fi"
            insertbefore: EOF
      when: make_persistent | bool

  handlers:
    - name: Restart network service
      ansible.builtin.service:
        name: network
        state: restarted
      when: make_persistent | bool
