################################################################################
# Optimizes network settings for z/PDT systems
#
# Requirements:
# - Ansible 2.9+
# - Root access
# - RHEL system
#
# Usage:
# ansible-playbook -i inventories/inventory.yml optimize_zpdt_network.yml --ask-become-pass
# Optional: -e "network_interface=eth0 make_persistent=true"
################################################################################

---
- name: nuc Network Optimization
  hosts: nuc
  become: yes
  gather_facts: yes

  vars:
    network_interface: eno1
    offload_options:
      - rx
      - tso
      - gso
      - gro
      - lro
    make_persistent: false

  tasks:
    - name: Ensure ethtool is installed
      ansible.builtin.package:
        name: ethtool
        state: present

    - name: Verify network interface exists
      ansible.builtin.command: "ip link show {{ network_interface }}"
      register: interface_check
      failed_when: interface_check.rc != 0
      changed_when: false

    - name: Disable network offload options
      ansible.builtin.command: "ethtool -K {{ network_interface }} {{ item }} off"
      loop: "{{ offload_options }}"
      register: disable_result
      changed_when: "'Actual changes' in disable_result.stderr"
      failed_when: 
        - disable_result.rc != 0
        - "'Cannot change' not in disable_result.stderr"

    - name: Make changes persistent
      block:
        - name: Create network scripts directory
          ansible.builtin.file:
            path: /etc/sysconfig/network-scripts
            state: directory
            mode: '0755'

        - name: Create or update ifup-local script
          ansible.builtin.template:
            src: ifup-local.j2
            dest: /etc/sysconfig/network-scripts/ifup-local
            mode: '0755'
          vars:
            interface: "{{ network_interface }}"
            options: "{{ offload_options }}"

        - name: Ensure ifup-local is executed
          ansible.builtin.lineinfile:
            path: /etc/sysconfig/network-scripts/ifup
            line: "if [ -x /etc/sysconfig/network-scripts/ifup-local ]; then /etc/sysconfig/network-scripts/ifup-local ${DEVICE}; fi"
            insertbefore: EOF
      when: make_persistent | bool

  handlers:
    - name: Restart network service
      ansible.builtin.service:
        name: network
        state: restarted
      when: make_persistent | bool