################################################################################
# Creates volumes for z/PDT systems
#
# Requirements:
# - Ansible 2.9+
# - alcckd command available
#
# Usage:
# ansible-playbook -i inventory.yml provision_volumes.yml
# Optional: -e "dest_dir=/custom/volume/path"
################################################################################

---
- name: zPDT Volume Provisioning
  hosts: zPDT
  gather_facts: yes

  vars:
    dest_dir: "/home/ibmsys1/volumes-z31a"
    volumes_3390_27:
      - a3usr2
      - a3usr3
      - a3usr4
      - a3usr5
      - a3zcx2
    volumes_3390_9:
      - work0a

  tasks:
    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: "{{ dest_dir }}"
        state: directory
        mode: '0755'

    - name: Create 3390-27 volumes
      ansible.builtin.command: "alcckd {{ dest_dir }}/{{ item }} -d3390-27"
      loop: "{{ volumes_3390_27 }}"
      register: create_3390_27_result
      failed_when: create_3390_27_result.rc != 0
      changed_when: create_3390_27_result.rc == 0

    - name: Create 3390-9 volumes
      ansible.builtin.command: "alcckd {{ dest_dir }}/{{ item }} -d3390-9"
      loop: "{{ volumes_3390_9 }}"
      register: create_3390_9_result
      failed_when: create_3390_9_result.rc != 0
      changed_when: create_3390_9_result.rc == 0

    - name: Verify volume creation
      ansible.builtin.stat:
        path: "{{ dest_dir }}/{{ item }}"
      loop: "{{ volumes_3390_27 + volumes_3390_9 }}"
      register: volume_check
      failed_when: not volume_check.stat.exists