################################################################################
# Creates volumes for z/PDT systems
#
# Requirements:
# - Ansible 2.9+
# - alcckd command available
#
# Usage:
# ansible-playbook -i inventories/inventory.yml provision_volumes.yml
# Optional: -e "dest_dir=/custom/volume/path"
################################################################################

---
- name: zPDT Volume Provisioning
  hosts: zPDT
  gather_facts: yes

  vars:
    dest_dir: "/home/ibmsys1/volumes-z31c"
    volumes_3390_54:
      - c3usr2
      - c3usr3
      - c3usr4
      - c3usr5
      - c3zcx2
    volumes_3390_9:
      - work0a

  tasks:
    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: "{{ dest_dir }}"
        state: directory
        mode: '0755'

    - name: Create 3390-54 volumes
      ansible.builtin.command: "alcckd {{ dest_dir }}/{{ item }} -d3390-54"
      loop: "{{ volumes_3390_54 }}"
      register: create_3390_54_result
      failed_when: create_3390_54_result.rc != 0
      changed_when: create_3390_54_result.rc == 0

    - name: Create 3390-9 volumes
      ansible.builtin.command: "alcckd {{ dest_dir }}/{{ item }} -d3390-9"
      loop: "{{ volumes_3390_9 }}"
      register: create_3390_9_result
      failed_when: create_3390_9_result.rc != 0
      changed_when: create_3390_9_result.rc == 0

    - name: Verify volume creation
      ansible.builtin.stat:
        path: "{{ dest_dir }}/{{ item }}"
      loop: "{{ volumes_3390_54 + volumes_3390_9 }}"
      register: volume_check
      failed_when: not volume_check.stat.exists