# restore_volumes.yml
#
# This Ansible playbook unarchives a specified backup file to the specified
# destination directory.
#
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Example:
#  ansible-playbook -i inventories restore_volumes.yml
#  ansible-playbook -i inventories restore_volumes.yml -v
---
- name: Restore volumes from backup
  hosts: rhel
  vars:
    backup_file: "/home/ibmsys1/volumes-backup/volumes-z25c-20230111.zip"
    dest_dir: "/home/ibmsys1/transfers-zPDT"

  tasks:
    - name: Unarchive z25c volumes
      ansible.builtin.unarchive:
        src: "{{ backup_file }}"
        dest: "{{ dest_dir }}"
        remote_src: yes

