################################################################################
# Playbook Name: Set up zOS Housekeeping Cron Job
#
# Purpose:
#   This playbook automates the setup of a cron job for zOS housekeeping tasks on a zPDT system.
#   It performs the following tasks:
#   - Creates a cron job scheduled to run at a specified time on specified days
#   - Sets up the cron job to execute another Ansible playbook (zos_housekeeping.yml)
#   - Ensures the cron job runs with appropriate user permissions
#
# Requirements:
#   - Ansible 2.9 or higher
#   - Access to zPDT system with appropriate permissions
#   - The zos_housekeeping.yml playbook must exist at the specified path
#   - Sudo access on the target system
#
# Usage:
#   Basic execution (with sudo password prompt):
#     ansible-playbook -i inventories/inventory.yml setup_zos_housekeeping_cron.yml --ask-become-pass
#
#   With increased verbosity:
#     ansible-playbook -i inventories/inventory.yml setup_zos_housekeeping_cron.yml --ask-become-pass -v
#
#   With custom variables:
#     ansible-playbook -i inventories/inventory.yml setup_zos_housekeeping_cron.yml --ask-become-pass -e "cron_minute=30 cron_hour=8 cron_weekday=1,4,5"
#
# Variables:
#   cron_minute: Minute when the cron job should run (default: "0")
#   cron_hour: Hour when the cron job should run (default: "7")
#   cron_weekday: Days of the week when the cron job should run (default: "1,3,5")
#   cron_user: User who should run the cron job (default: "ibmsys1")
#   ansible_playbook_path: Path to the ansible-playbook executable (default: "/usr/bin/ansible-playbook")
#   inventory_file: Path to the inventory file (default: "/home/ibmsys1/GitHub/ansible-playbooks/ansible-playbooks-zos/inventories/inventory.yml")
#   housekeeping_playbook: Path to the housekeeping playbook (default: "/home/ibmsys1/GitHub/ansible-playbooks/ansible-playbooks-zos/zos_housekeeping.yml")
#
################################################################################
---
- name: Set up zOS Housekeeping Cron Job
  hosts: zPDT
  vars_files:
    - su_secrets.yml
  vars:
    cron_minute: "0"
    cron_hour: "7"
    cron_weekday: "1,3,5"
    cron_user: "ibmsys1"
    ansible_playbook_path: "/usr/bin/ansible-playbook"
    inventory_file: "/home/ibmsys1/GitHub/ansible-playbooks/ansible-playbooks-zos/inventories/inventory.yml"
    housekeeping_playbook: "/home/ibmsys1/GitHub/ansible-playbooks/ansible-playbooks-zos/zos_housekeeping.yml"
  become: yes
  gather_facts: yes

  tasks:
    - name: Ensure required files exist
      stat:
        path: "{{ item }}"
      register: file_check
      loop:
        - "{{ inventory_file }}"
        - "{{ housekeeping_playbook }}"

    - name: Fail if required files are missing
      fail:
        msg: "Required file {{ item.item }} does not exist"
      when: not item.stat.exists
      loop: "{{ file_check.results }}"

    - name: Create cron job for zOS Housekeeping
      cron:
        name: "zOS Housekeeping"
        minute: "{{ cron_minute }}"
        hour: "{{ cron_hour }}"
        weekday: "{{ cron_weekday }}"
        job: "{{ ansible_playbook_path }} -i {{ inventory_file }} {{ housekeeping_playbook }}"
        user: "{{ cron_user }}"
      register: cron_result

    - name: Display cron job creation result
      debug:
        var: cron_result
        verbosity: 1

    - name: Verify cron job creation
      fail:
        msg: "Failed to create cron job"
      when: cron_result is failed

    - name: Success message
      debug:
        msg: "zOS Housekeeping cron job has been successfully set up"