################################################################################
# Sets up cron job for zOS housekeeping tasks
#
# Usage:
# ansible-playbook -i inventories/inventory.yml setup_zos_housekeeping_cron.yml --ask-become-pass
# Optional: -e "cron_minute=30 cron_hour=8 cron_weekday=1,4,5"
################################################################################

---
- name: Set up zOS Housekeeping Cron Job
  hosts: zPDT
  vars_files:
    - su_secrets.yml
  vars:
    cron_minute: "0"
    cron_hour: "1"
    cron_weekday: "*"
    cron_user: "ibmsys1"

  become: yes
  gather_facts: yes

  tasks:
    - name: Create cron job for zOS Housekeeping
      cron:
        name: "zOS Housekeeping"
        minute: "{{ cron_minute }}"
        hour: "{{ cron_hour }}"
        weekday: "{{ cron_weekday }}"
        job: "ansible-playbook -i /etc/ansible/inventory.yml zos_housekeeping.yml"
        user: "{{ cron_user }}"