################################################################################
# Playbook: Set up zOS Housekeeping Cron Job
#
# Purpose: Automates the setup of a cron job for zOS housekeeping tasks on a zPDT system.
#
# Requirements:
# - Ansible 2.9+
# - Access to zPDT system with sudo privileges
# - zos_housekeeping.yml playbook at specified path
#
# Usage:
# ansible-playbook -i inventories/inventory.yml setup_zos_housekeeping_cron.yml --ask-become-pass
#
# Variables:
# cron_minute: Minute to run (default: "0")
# cron_hour: Hour to run (default: "7")
# cron_weekday: Days to run (default: "1,3,5")
# cron_user: User to run as (default: "ibmsys1")
# ansible_playbook_path: Path to ansible-playbook (default: "/usr/bin/ansible-playbook")
# inventory_file: Path to inventory file
# housekeeping_playbook: Path to housekeeping playbook
#
# Key Tasks:
# 1. Verify required files exist
# 2. Create cron job for zOS Housekeeping
# 3. Verify cron job creation
#
# Error Handling:
# - Fails if required files are missing
# - Verifies successful cron job creation
#
# Notes:
# - Uses su_secrets.yml for sensitive data
# - Runs with sudo privileges
#
# Examples:
#   1. Run with default settings:
#      ansible-playbook -i inventories/inventory.yml setup_zos_housekeeping_cron.yml --ask-become-pass
#
#   2. Run with custom cron schedule:
#      ansible-playbook -i inventories/inventory.yml setup_zos_housekeeping_cron.yml --ask-become-pass -e "cron_minute=30 cron_hour=8 cron_weekday=1,4,5"
#
################################################################################
---
- name: Set up zOS Housekeeping Cron Job
  hosts: zPDT
  vars_files:
    - su_secrets.yml
  vars:
    cron_minute: "0"
    cron_hour: "7"
    cron_weekday: "1,3,5"
    cron_user: "ibmsys1"
    ansible_playbook_path: "/usr/bin/ansible-playbook"
    inventory_file: "/home/ibmsys1/GitHub/ansible-playbooks/ansible-playbooks-zos/inventories/inventory.yml"
    housekeeping_playbook: "/home/ibmsys1/GitHub/ansible-playbooks/ansible-playbooks-zos/zos_housekeeping.yml"
  become: yes
  gather_facts: yes

  tasks:
    - name: Ensure required files exist
      stat:
        path: "{{ item }}"
      register: file_check
      loop:
        - "{{ inventory_file }}"
        - "{{ housekeeping_playbook }}"

    - name: Fail if required files are missing
      fail:
        msg: "Required file {{ item.item }} does not exist"
      when: not item.stat.exists
      loop: "{{ file_check.results }}"

    - name: Create cron job for zOS Housekeeping
      cron:
        name: "zOS Housekeeping"
        minute: "{{ cron_minute }}"
        hour: "{{ cron_hour }}"
        weekday: "{{ cron_weekday }}"
        job: "{{ ansible_playbook_path }} -i {{ inventory_file }} {{ housekeeping_playbook }}"
        user: "{{ cron_user }}"
      register: cron_result

    - name: Display cron job creation result
      debug:
        var: cron_result
        verbosity: 1

    - name: Verify cron job creation
      fail:
        msg: "Failed to create cron job"
      when: cron_result is failed

    - name: Success message
      debug:
        msg: "zOS Housekeeping cron job has been successfully set up"