###############################################################################
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Example:
#  ansible-playbook -i inventory start_docker.yml
#  ansible-playbook -i inventory start_docker.yml -v
###############################################################################
---
- hosts: p52
  vars_files:
    - vault.yml
  tasks:

    - name: Start MQ Docker container
      docker_container:
        name: QM1
        image: icr.io/ibm-messaging/mq:latest
        state: started
        published_ports:
          - "1414:1414"
          - "9444:9443"
        volumes:
          - "qm1-data:/mnt/mqm"
        env:
          LICENSE: "accept"
          MQ_APP_PASSWORD: "passw0rd"

    - name: Start Jenkins Docker container
      docker_container:
        name: jenkins
        image: jenkins/jenkins:lts
        state: started
        published_ports:
          - "9080:8080"
          - "50000:50000"
        volumes:
          - "jenkins-data:/var/jenkins_home"

    - name: Start dockerManageZdap script
      shell: "/home/ibmsys1/docker-compose/bin/dockerManageZdap.sh up"

    - name: Execute command to start UCD server
      ansible.builtin.command:
        cmd: "/opt/ucd/server/bin/server start"
      become: yes  
      register: result

    - name: Display result of command execution
      debug:
        var: result.stdout_lines
