###############################################################################
# Playbook: start_containers_and_services.yml
#
# Purpose:
#  This playbook starts specified Docker containers (MQ and Jenkins)
#  and starts services (dockerManageZdap and UCD server) on target hosts.
#
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Required Variables:
#  - vault.yml: an Ansible Vault encrypted file containing the sudo password
#               for the target hosts (variable: ansible_become_password).
#
# Example:
#  ansible-playbook -i inventory start_containers_and_services.yml --ask-vault-pass
#  ansible-playbook -i inventory start_containers_and_services.yml -v --ask-vault-pass
###############################################################################
---
- hosts: p52
  vars_files:
    - vault.yml
  tasks:
    - name: Start MQ Docker container
      docker_container:
        name: QM1
        image: icr.io/ibm-messaging/mq:latest
        state: started
        published_ports:
          - "1414:1414"
          - "9444:9443"
        volumes:
          - "qm1-data:/mnt/mqm"
        env:
          LICENSE: "accept"
          MQ_APP_PASSWORD: "passw0rd"

    - name: Start Jenkins Docker container
      docker_container:
        name: jenkins
        image: jenkins/jenkins:lts
        state: started
        published_ports:
          - "9080:8080"
          - "50000:50000"
        volumes:
          - "jenkins-data:/var/jenkins_home"

    - name: Start dockerManageZdap script
      ansible.builtin.command:
        cmd: "/home/ibmsys1/docker-compose/bin/dockerManageZdap.sh up"
      register: docker_manage_result

    - name: Display dockerManageZdap script result
      debug:
        var: docker_manage_result.stdout_lines

    - name: Start UCD server
      ansible.builtin.command:
        cmd: "/opt/ucd/server/bin/server start"
      become: yes
      register: ucd_server_result

    - name: Display UCD server start result
      debug:
        var: ucd_server_result.stdout_lines
