# Playbook: start_containers_and_services.yml
#
# Purpose:
#  This playbook starts specified Docker containers (MQ and Jenkins)
#  and starts services (dockerManageZdap and UCD server) on target hosts.
#
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Required Variables:
#  - vault.yml: an Ansible Vault encrypted file containing the sudo password
#               for the target hosts (variable: ansible_become_password).
#
# Example:
#  ansible-playbook -i inventories start_containers_and_services.yml --ask-vault-pass
#  ansible-playbook -i inventories start_containers_and_services.yml -v --ask-vault-pass
---
- hosts: p52
  vars_files:
    - vault.yml
  tasks:
    # Start IBM MQ Docker container
    - name: Ensure MQ Docker container is started
      docker_container:
        name: QM1
        image: icr.io/ibm-messaging/mq:latest
        state: started
        published_ports:
          - "1414:1414"
          - "9444:9443"
        volumes:
          - "qm1-data:/mnt/mqm"
        env:
          LICENSE: "accept"
          MQ_APP_PASSWORD: "passw0rd"

    # Execute dockerManageZdap script
    - name: Execute dockerManageZdap script (up command)
      ansible.builtin.command:
        cmd: "/home/ibmsys1/docker-compose/bin/dockerManageZdap.sh up"
      register: docker_manage_result

    # Display the result of the dockerManageZdap script execution
    - name: Show dockerManageZdap script output
      debug:
        var: docker_manage_result.stdout_lines

    # Start UCD server
    - name: Ensure UCD server is started
      ansible.builtin.command:
        cmd: "/opt/ucd/server/bin/server start"
      become: yes
      register: ucd_server_result

    # Display the result of the UCD server start command
    - name: Show UCD server start output
      debug:
        var: ucd_server_result.stdout_lines