################################################################################
# Validates zOS Housekeeping cron job execution status
#
# Usage:
# ansible-playbook -i inventory.yml validate_zos_housekeeping_cron.yml --ask-become-pass
################################################################################

---
- name: Validate zOS Housekeeping Cron Job Execution
  hosts: zPDT
  become: yes
  gather_facts: yes
  vars:
    cron_job_name: "zOS Housekeeping"
    cron_output_file: "/var/log/zos_housekeeping_cron.log"
    log_file: "/var/log/cron"

  tasks:
    - name: Check system logs for cron job execution
      shell: "grep {{ cron_job_name | quote }} {{ log_file }} || echo 'No matches found'"
      register: log_check
      changed_when: false

    - name: Check cron job output file
      stat:
        path: "{{ cron_output_file }}"
      register: output_file

    - name: Display cron job output file contents
      command: "tail -n 20 {{ cron_output_file }}"
      register: output_content
      when: output_file.stat.exists
      changed_when: false

    - name: List crontab entries
      shell: |
        for user in $(cut -f1 -d: /etc/passwd); do 
          crontab -u "$user" -l 2>/dev/null | grep {{ cron_job_name | quote }} || true
        done
      register: crontab_entries
      changed_when: false