###############################################################################
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Example:
#  ansible-playbook -i inventory base_proclib.yml
#  ansible-playbook -i inventory base_proclib.yml -v
###############################################################################
---
- hosts: s0w1 
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  vars:
    adcd_ver: Z25A

  environment: "{{ environment_vars }}"

  tasks:
    - name: Ping using zos_ping
      zos_ping:
      register: zos_ping_result

    - name: Response from zos_ping
      debug:
        msg: "{{ zos_ping_result }}"

###############################################################################
# Usage:
#  Copy ADCD.{{ adcd_ver }}.PROCLIB(VTAMALL) to USER.{{ adcd_ver }}.PROCLIB(VTAMALL)
#  Alter VTAMALL PARMLIB DD to reference USER.&SYSVER..PARMLIB(&M)
###############################################################################

    - name: Copy VTAMALL from ADCD to USER; replace if it already exists.
      zos_copy:
        src: ADCD.{{ adcd_ver }}.PROCLIB(VTAMALL)
        dest: USER.{{ adcd_ver }}.PROCLIB(VTAMALL)
        remote_src: true
      register: zos_copy_result

    - name: DEBUG(-v) Response from Copy VTAMALL from ADCD to USER.
      debug:
        msg: "{{ zos_copy_result }} with verbosity 1"
        verbosity: 1

    - name: Update PARMLIB DD for VTAMALL.
      zos_lineinfile:
        src: USER.{{ adcd_ver }}.PROCLIB(VTAMALL)
        regexp: '^//PARMLIB'
        line: '//PARMLIB  DD  DSN=USER.&SYSVER..PARMLIB(&M),DISP=SHR'
      register: zos_lineinfile_result

    - name: DEBUG(-v) Response from Update PARMLIB DD for VTAMALL.
      debug:
        msg: "{{ zos_lineinfile_result }} with verbosity 1"
        verbosity: 1

###############################################################################
# Usage:
#  Copy ADCD.{{ adcd_ver }}.PROCLIB(SHUTALL) to USER.{{ adcd_ver }}.PROCLIB(SHUTALL)
#  Alter SHUTALL PARMLIB DD to reference USER.&SYSVER..PARMLIB(&M)
###############################################################################

    - name: Copy SHUTALL from ADCD to USER; replace if it already exists.
      zos_copy:
        src: ADCD.{{ adcd_ver }}.PROCLIB(SHUTALL)
        dest: USER.{{ adcd_ver }}.PROCLIB(SHUTALL)
        remote_src: true
      register: zos_copy_result

    - name: DEBUG(-v) Response from Copy SHUTALL from ADCD to USER.
      debug:
        msg: "{{ zos_copy_result }} with verbosity 1"
        verbosity: 1

    - name: Update PARMLIB DD for SHUTALL.
      zos_lineinfile:
        src: USER.{{ adcd_ver }}.PROCLIB(SHUTALL)
        regexp: '^//PARMLIB'
        line: '//PARMLIB  DD  DSN=USER.&SYSVER..PARMLIB(&M),DISP=SHR'
      register: zos_lineinfile_result

    - name: DEBUG(-v) Response from Update PARMLIB DD for SHUTALL.
      debug:
        msg: "{{ zos_lineinfile_result }} with verbosity 1"
        verbosity: 1

###############################################################################
# Usage:
#  Copy ADCD.{{ adcd_ver }}.PROCLIB(DBSPROCC) to USER.{{ adcd_ver }}.PROCLIB(DBSPROCC)
###############################################################################

    - name: Copy DBSPROCC from ADCD to USER; replace if it already exists.
      zos_copy:
        src: ADCD.{{ adcd_ver }}.PROCLIB(DBSPROCC)
        dest: USER.{{ adcd_ver }}.PROCLIB(DBSPROCC)
        remote_src: true
      register: zos_copy_result

    - name: DEBUG(-v) Response from Copy DBSPROCC from ADCD to USER.
      debug:
        msg: "{{ zos_copy_result }} with verbosity 1"
        verbosity: 1
 