###############################################################################
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Example:
#  ansible-playbook -i inventories base_auto_mount.yml
#  ansible-playbook -i inventories base_auto_mount.yml -v
###############################################################################
---
- hosts: ben_s0w1 
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  vars:
    adcd_ver: Z25C

  environment: "{{ environment_vars }}"

  tasks:
    - name: Ping using zos_ping
      zos_ping:
      register: zos_ping_result

    - name: Response from zos_ping
      debug:
        msg: "{{ zos_ping_result }}"

###############################################################################
# Usage:
#  Backup rc file to /tmp
###############################################################################

    - name: Backup file rc.
      zos_copy:
        src: /etc/rc
        dest: /tmp/rc-delete
        remote_src: true 
      register: zos_copy_result

    - name: DEBUG(-v) Response from Backup file rc.
      debug:
        msg: "{{ zos_copy_result }} with verbosity 1"
        verbosity: 1

###############################################################################
# Usage:
#  Load automount default policy 
###############################################################################

    - name: Insert automount facility.
      zos_blockinfile:
        src: /etc/rc
        insertafter: "chmod 1755 /dev"
        block: |
          # Start the automount facility
          /usr/sbin/automount
      register: zos_blockinfile_result

    - name: DEBUG(-v) Response from Insert automount facility.
      debug:
        msg: "{{ zos_blockinfile_result }} with verbosity 1"
        verbosity: 1

###############################################################################
# Usage:
#  Create empty file /etc/auto.master 
#  /u/automount directory is to be configured, along with the MapName file.
###############################################################################

    - name: Add directory and MapName file.
      shell: |
         echo "/u/automount      /etc/u.map" > /etc/auto.master
      register: zos_shell

    - name: DEBUG(-v) Response from Add directory and MapName file.
      debug:
        msg: "{{ zos_shell }} with verbosity 1"
        verbosity: 1

###############################################################################
# Usage:
#   Create empty file /etc/u.map
#   ZFS attributes related to /u directory  
###############################################################################

    - name: Add ZFS attributes.
      shell: |
         echo "name                             *" > /etc/u.map
         echo "type                             ZFS" >> /etc/u.map
         echo "filesystem                       OMVS.<uc_name>.&SYSNAME..ZFS" >> /etc/u.map
         echo "mode                             rdwr" >> /etc/u.map
         echo "duration                         30" >> /etc/u.map
         echo "delay                            10" >> /etc/u.map
         echo "allocany space(1,1) cyl unit(disk) pathperm(775) euid ucat" >> /etc/u.map         
      register: zos_shell

    - name: DEBUG(-v) Response from Add ZFS attributes.
      debug:
        msg: "{{ zos_shell }} with verbosity 1"
        verbosity: 1

###############################################################################
# Usage:
#  Define catalog ALIAS OMVS
###############################################################################

    - name: Define alias OMVS.
      zos_tso_command:
        commands:
          - DEFINE ALIAS (NAME('OVMS') RELATE('USERCAT.{{ adcd_ver }}.USER'))
      ignore_errors: true
      register: zos_tso_command_result

    - name: DEBUG(-v) Response from Define alias OMVS.
      debug:
        msg: "{{ zos_tso_command_result }} with verbosity 1"
        verbosity: 1