###############################################################################
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Example:
#  ansible-playbook -i inventory base_auto_mount.yml
#  ansible-playbook -i inventory base_auto_mount.yml -v
###############################################################################
---
- hosts: ben_s0w1 
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  vars:
    adcd_ver: Z25A

  environment: "{{ environment_vars }}"

  tasks:
    - name: Ping using zos_ping
      zos_ping:
      register: zos_ping_result

    - name: Response from zos_ping
      debug:
        msg: "{{ zos_ping_result }}"

###############################################################################
# Usage:
#  Backup rc file to /tmp
###############################################################################

    - name: Backup file rc.
      zos_copy:
        src: /etc/rc
        dest: /tmp/rc-delete
        remote_src: true 
      register: zos_copy_result

    - name: DEBUG(-v) Response from Backup file rc.
      debug:
        msg: "{{ zos_copy_result }} with verbosity 1"
        verbosity: 1

###############################################################################
# Usage:
#  Load automount default policy 
###############################################################################

    - name: Insert automount facility.
      zos_blockinfile:
        src: /etc/rc
        insertafter: "chmod 1755 /dev"
        block: |
          # Start the automount facility
          /usr/sbin/automount
      register: zos_blockinfile_result

    - name: DEBUG(-v) Response from Insert automount facility.
      debug:
        msg: "{{ zos_blockinfile_result }} with verbosity 1"
        verbosity: 1

###############################################################################
# Usage:
#  Create empty file /etc/auto.master 
#  /u directory is to be configured, along with the MapName file.
###############################################################################

    - name: Touch file /etc/auto.master.
      file:
        path: /etc/auto.master
        state: touch
      register: file_result

    - name: DEBUG(-v) Response from Touch file /etc/auto.master.
      debug:
        msg: "{{ file_result }} with verbosity 1"
        verbosity: 1

    - name: Add directory and MapName file.
      zos_blockinfile:
        src: /etc/auto.master
        marker: "/* {mark} ANSIBLE MANAGED BLOCK"
        block: |
          /u                /etc/u.map
      register: zos_blockinfile_result

    - name: DEBUG(-v) Response from Add directory and MapName file.
      debug:
        msg: "{{ zos_blockinfile_result }} with verbosity 1"
        verbosity: 1

###############################################################################
# Usage:
#   Create empty file /etc/u.map
#   ZFS attributes related to /u directory  
###############################################################################

    - name: Touch file /etc/u.map.
      file:
        path: /etc/u.map
        state: touch
      register: file_result

    - name: DEBUG(-v) Response from Touch file /etc/u.map.
      debug:
        msg: "{{ file_result }} with verbosity 1"
        verbosity: 1

    - name: Add ZFS attributes.
      zos_blockinfile:
        src: /etc/u.map
        marker: "* {mark} ANSIBLE MANAGED BLOCK"
        block: |
          name                             *
          type                             ZFS
          filesystem                       <uc_name>.&SYSNAME..ZFS
          mode                             rdwr
          duration                         30
          delay                            10
          allocany space(1,1) cyl unit(disk) pathperm(775) euid ucat
      register: zos_blockinfile_result

    - name: DEBUG(-v) Response from Add ZFS attributes.
      debug:
        msg: "{{ zos_blockinfile_result }} with verbosity 1"
        verbosity: 1

