################################################################################
# Sets up CICS EGUI environment on z/OS
#
# Requirements:
# - IBM z/OS Core Collection
# - JCL members in IBMUSER.GIT.JCL.CNTL
#
# Usage:
# ansible-playbook -i inventories/inventory.yml cics_egui_setup.yml
################################################################################

---
- name: CICS EGUI Setup
  hosts: z31a_s0w1
  collections:
    - ibm.ibm_zos_core
  gather_facts: yes

  vars:
    jcl_library: IBMUSER.GIT.JCL.CNTL
    wait_time_seconds: 120
    max_rc: 0
    cics_sip_dataset: DFH610.SYSIN(DFH$SIP1)
    dfltuser: IBMUSER

  environment: "{{ environment_vars }}"

  tasks:
    - name: Verify connectivity
      zos_ping:

    - name: Create and define VSAM data sets
      block:
        - name: Submit DFH$ECAT job
          zos_job_submit:
            src: "{{ jcl_library }}(DFH$ECAT)"
            location: DATA_SET
            wait_time_s: "{{ wait_time_seconds }}"
            max_rc: "{{ max_rc }}"

        - name: Submit DFH$ECNF job
          zos_job_submit:
            src: "{{ jcl_library }}(DFH$ECNF)"
            location: DATA_SET
            wait_time_s: "{{ wait_time_seconds }}"
            max_rc: "{{ max_rc }}"

    - name: Submit CICS system definition for zOffice
      zos_job_submit:
        src: "{{ jcl_library }}(CICSCSD)"
        location: DATA_SET
        wait_time_s: "{{ wait_time_seconds }}"
        max_rc: "{{ max_rc }}"

    - name: Configure CICS SIP
      zos_lineinfile:
        src: "{{ cics_sip_dataset }}"
        insertbefore: '^*TCPIP=YES'
        line: 'DFLTUSER={{ dfltuser }}                          ANSIBLE ADDED {{ dfltuser }}'