################################################################################
# Customizes COBOL procedures on z/OS
#
# Requirements:
# - IBM z/OS Core Collection
# - COBOL compiler installed
#
# Usage:
# ansible-playbook -i inventories/inventory.yml COBOL_Customization_Setup.yml
################################################################################

---
- name: COBOL Customization Setup
  hosts: ben_s0w1 
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  vars:
    adcd_ver: Z25C
    cobol_hlq: IGY640

  environment: "{{ environment_vars }}"

  tasks:
    - name: Copy COBOL procedures to USER PROCLIB
      zos_copy:
        src: "{{ cobol_hlq }}.SIGYPROC({{ item }})"
        dest: "USER.{{ adcd_ver }}.PROCLIB({{ item }})"
        remote_src: true
      loop:
        - IGYQC
        - IGYQCB
        - IGYQCBG

    - name: Update IGYQC procedure
      zos_lineinfile:
        src: "USER.{{ adcd_ver }}.PROCLIB(IGYQC)"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        insertafter: "{{ item.insertafter | default(omit) }}"
      loop:
        - { regexp: "^//             LIBPRF1=&LIBPRFX", line: "//             LIBPRF1=&LIBPRFX," }
        - { insertafter: "^//             LIBPRF1=&LIBPRFX,", line: "//             CPARM=''" }
        - { regexp: "^//COBOL  EXEC PGM=IGYCRCTL,REGION=0M", line: "//COBOL  EXEC PGM=IGYCRCTL,REGION=0M,PARM='&CPARM'" }

    - name: Update IGYQCB procedure
      zos_lineinfile:
        src: "USER.{{ adcd_ver }}.PROCLIB(IGYQCB)"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        insertafter: "{{ item.insertafter | default(omit) }}"
      loop:
        - { regexp: "^//             PGMLIB='&&GOSET',GOPGM=GO", line: "//             PGMLIB='&&GOSET'," }
        - { insertafter: "^//             PGMLIB='&&GOSET',", line: "//             CPARM=''," }
        - { insertafter: "^//             CPARM='',", line: "//             GOPGM=GO" }
        - { regexp: "^//COBOL  EXEC PGM=IGYCRCTL,REGION=0M", line: "//COBOL  EXEC PGM=IGYCRCTL,REGION=0M,PARM='&CPARM'" }

    - name: Update IGYQCBG procedure
      zos_lineinfile:
        src: "USER.{{ adcd_ver }}.PROCLIB(IGYQCBG)"
        regexp: "{{ item.regexp | default(omit) }}"
        line: "{{ item.line }}"
        insertafter: "{{ item.insertafter | default(omit) }}"
        insertbefore: "{{ item.insertbefore | default(omit) }}"
      loop:
        - { insertafter: "^//             LIBPRF1=&LIBPRFX,", line: "//             CPARM=''," }
        - { insertafter: "^//             BPARM='LIST=NOIMP',", line: "//             GPARM=''," }
        - { regexp: "^//COBOL  EXEC PGM=IGYCRCTL,REGION=0M", line: "//COBOL  EXEC PGM=IGYCRCTL,REGION=0M,PARM='&CPARM'" }
        - { regexp: "^//       REGION=0M", line: "//       REGION=0M,PARM='&GPARM'" }
        - { insertbefore: "^//STEPLIB  DD  DSNAME=&LIBPRF1..SCEERUN2,DISP=SHR", line: "//STEPLIB  DD  DSNAME=ISM330.SEQAMOD,DISP=SHR" }
        - { regexp: "^//STEPLIB  DD  DSNAME=&LIBPRF1..SCEERUN2,DISP=SHR", line: "//         DD  DSNAME=&LIBPRF1..SCEERUN2,DISP=SHR" }