################################################################################
# Copies IBMPRODS member from ADCD to USER ISPPLIB for DB2 V13
#
# Usage:
# ansible-playbook -i inventory.yml copy_ibmprods_ispplib.yml
################################################################################

---
- name: Copy IBMPRODS ISPPLIB
  hosts: z31a_s0w1
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  vars:
    adcd_ver: Z31A

  environment: "{{ environment_vars }}"

  tasks:
    - name: Copy IBMPRODS from ADCD to USER ISPPLIB
      zos_copy:
        src: "ADCD.{{ adcd_ver }}.DBD.ISPPLIB(IBMPRODS)"
        dest: "USER.{{ adcd_ver }}.ISPPLIB(IBMPRODS)"
        remote_src: true