################################################################################
# Playbook Name: Copy IBMPRODS ISPPLIB
#
# Purpose:
#   This playbook automates the copying of the IBMPRODS member from the ADCD
#   ISPPLIB to the USER ISPPLIB on a z/OS system. This is typically used for
#   customizing Db2 V13 ISPF panels.
#
# Requirements:
#   - Ansible 2.9 or higher
#   - IBM z/OS Core Collection (ibm.ibm_zos_core) installed
#   - Access to z/OS system with appropriate permissions
#   - Proper setup of Ansible inventory file with z/OS target information
#
# Usage:
#   Basic execution:
#     ansible-playbook -i <inventory_file> copy_ibmprods_ispplib.yml
#
#   With increased verbosity:
#     ansible-playbook -i <inventory_file> copy_ibmprods_ispplib.yml -v
#
# Variables:
#   adcd_ver: ADCD version (default: Z31A)
#   src_hlq: High-level qualifier for the source dataset (default: ADCD)
#   dest_hlq: High-level qualifier for the destination dataset (default: USER)
#
# Notes:
#   - Ensure that the necessary permissions and system access are in place before running.
#   - Review and adjust the variables as needed for your environment.
#   - The playbook will replace the IBMPRODS member in the destination ISPPLIB if it already exists.
#   - Debug messages are displayed only in verbose mode (-v).
#   - The playbook includes error handling and will provide detailed error messages if issues occur.
#
# Examples:
#   1. Run the playbook with default settings:
#      ansible-playbook -i inventory.ini copy_ibmprods_ispplib.yml
#
#   2. Run the playbook with verbose output:
#      ansible-playbook -i inventory.ini copy_ibmprods_ispplib.yml -v
#
#   3. Run the playbook with custom ADCD version and HLQs:
#      ansible-playbook -i inventory.ini copy_ibmprods_ispplib.yml -e "adcd_ver=Z32A src_hlq=PROD dest_hlq=TEST"
#
################################################################################

---
- name: Copy IBMPRODS ISPPLIB
  hosts: z31a_s0w1
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  vars:
    adcd_ver: Z31A
    src_hlq: ADCD
    dest_hlq: USER

  environment: "{{ environment_vars }}"

  tasks:
    - name: Verify connectivity
      zos_ping:
      register: zos_ping_result

    - name: Display ping response
      debug:
        var: zos_ping_result
        verbosity: 1

    - name: Validate variables
      assert:
        that:
          - adcd_ver is string
          - src_hlq is string
          - dest_hlq is string
        fail_msg: "Invalid variable type. All variables should be strings."
        success_msg: "All variables validated successfully."

    - name: Copy IBMPRODS from source to destination ISPPLIB
      block:
        - name: Copy IBMPRODS member
          zos_copy:
            src: "{{ src_hlq }}.{{ adcd_ver }}.DBD.ISPPLIB(IBMPRODS)"
            dest: "{{ dest_hlq }}.{{ adcd_ver }}.ISPPLIB(IBMPRODS)"
            remote_src: true
          register: copy_result
      rescue:
        - name: Log IBMPRODS copy errors
          debug:
            msg: "Error occurred during IBMPRODS copy: {{ ansible_failed_result }}"
          failed_when: true
      always:
        - name: Display copy operation result
          debug:
            var: copy_result
            verbosity: 1

    - name: Verify IBMPRODS member in destination
      zos_data_set:
        name: "{{ dest_hlq }}.{{ adcd_ver }}.ISPPLIB"
        type: member
        member: IBMPRODS
      register: verify_result

    - name: Display task summary
      debug:
        msg:
          - "Playbook execution summary:"
          - "- Connectivity check result: {{ zos_ping_result.ping }}"
          - "- IBMPRODS copy status: {{ 'Successful' if copy_result.changed else 'No Change Required' }}"
          - "- Source dataset: {{ src_hlq }}.{{ adcd_ver }}.DBD.ISPPLIB(IBMPRODS)"
          - "- Destination dataset: {{ dest_hlq }}.{{ adcd_ver }}.ISPPLIB(IBMPRODS)"
          - "- IBMPRODS member present in destination: {{ verify_result.exists }}"
        verbosity: 0

    - name: Final status check
      assert:
        that:
          - zos_ping_result.ping == "pong"
          - verify_result.exists
        fail_msg: "Playbook execution failed. Check the summary for details."
        success_msg: "Playbook executed successfully. IBMPRODS member copied and verified."