################################################################################
# Playbook: z/OS Configuration Tasks
# Purpose: Sets up JOBCARD REXX and modifies DBSPROC procedures
# Usage: ansible-playbook -i <inventory_file> zos_config.yml
################################################################################

---
- name: z/OS Configuration Tasks
  hosts: z31a_s0w1
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  vars:
    adcd_ver: Z31A

  environment: "{{ environment_vars }}"

  tasks:
    - name: Verify connectivity
      zos_ping:

    - name: Create and populate JOBCARD REXX
      block:
        - name: Create JOBCARD member
          zos_data_set:
            name: USER.{{ adcd_ver }}.SYSEXEC(JOBCARD)
            type: MEMBER
            replace: yes

        - name: Insert JOBCARD REXX content
          zos_blockinfile:
            src: USER.{{ adcd_ver }}.SYSEXEC(JOBCARD)
            block: |
              /* REXX */
              /* Insert JOBCARD to JCL in ISPF Edit */
              "ISREDIT MACRO"
              lineno = 0
              line = "//IU***** JOB (FB3),'********',CLASS=A,MSGCLASS=H,"
              "ISREDIT LINE_AFTER "lineno" = (line)"
              lineno = lineno + 1
              line = "//       NOTIFY=&SYSUID,REGION=0M,TIME=1440"
              "ISREDIT LINE_AFTER "lineno" = (line)"
              lineno = lineno + 1
              line = "//*      TYPRUN=HOLD"
              "ISREDIT LINE_AFTER "lineno" = (line)"
              Exit 0

        - name: Remove block markers
          zos_lineinfile:
            src: USER.{{ adcd_ver }}.SYSEXEC(JOBCARD)
            state: absent
            regexp: '^#'

    - name: Update DBSPROC procedures
      block:
        - name: Update DBSPROCC SYSEXEC DD
          zos_lineinfile:
            src: USER.{{ adcd_ver }}.PROCLIB(DBSPROCC)
            insertafter: '^//SYSEXEC'
            line: '//         DD  DISP=SHR,DSN=USER.&SYSVER..SYSEXEC'

        - name: Update DBSPROCD SYSEXEC DD
          zos_lineinfile:
            src: USER.{{ adcd_ver }}.PROCLIB(DBSPROCD)
            insertafter: '^//SYSEXEC'
            line: '//         DD  DISP=SHR,DSN=USER.&SYSVER..SYSEXEC'