################################################################################
# Playbook: DBB COBOL Dataset Creation
# Purpose: Creates required DBB datasets for COBOL development on z/OS
# Usage: ansible-playbook -i <inventory_file> dbb_datasets.yml
################################################################################

---
- name: Create DBB COBOL Datasets
  hosts: ben_s0w1
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  vars:
    hlq: IBMUSER.DBB
    primary_space: 1CYL
    secondary_space: 1CYL
    record_length: 80

  environment: "{{ environment_vars }}"

  tasks:
    - name: Verify connectivity
      zos_ping:

    - name: Create FB format datasets
      zos_data_set:
        name: "{{ hlq }}.{{ item }}"
        type: LIBRARY
        state: present
        format: fb
        size: "{{ primary_space }}"
        secondary: "{{ secondary_space }}"
        record_length: "{{ record_length }}"
        replace: yes
      loop:
        - COBOL
        - COPY
        - DBRM
        - BMS
        - LINK
        - OBJ

    - name: Create LOAD dataset
      zos_data_set:
        name: "{{ hlq }}.LOAD"
        type: LIBRARY
        state: present
        format: u
        size: "{{ primary_space }}"
        secondary: "{{ secondary_space }}"
        record_length: 0
        replace: yes

    - name: Display creation summary
      debug:
        msg: "Created datasets under {{ hlq }}: COBOL, COPY, DBRM, BMS, LINK, OBJ, and LOAD"