################################################################################
# Playbook: RMF Configuration
# Purpose: Configures RMF on z/OS system (ERBRMF00, VTAMALL, SHUTALL)
# Usage: ansible-playbook -i <inventory_file> rmf_config.yml
################################################################################

---
- name: RMF Configuration
  hosts: z31a_s0w1
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  vars:
    adcd_ver: Z31A

  environment: "{{ environment_vars }}"

  tasks:
    - name: Verify connectivity
      zos_ping:

    - name: Copy ERBRMF00 to USER PARMLIB
      zos_copy:
        src: SYS1.PARMLIB(ERBRMF00)
        dest: "USER.{{ adcd_ver }}.PARMLIB(ERBRMF00)"
        remote_src: true

    - name: Update ERBRMF00 parameters
      zos_lineinfile:
        src: "USER.{{ adcd_ver }}.PARMLIB(ERBRMF00)"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^  CACHE', line: '  NOCACHE                    /* CACHE   STATISTICS                   */' }
        - { regexp: '^  CHAN', line: '  NOCHAN                     /* CHANNEL STATISTICS                   */' }
        - { regexp: '^  CRYPTO', line: '  NOCRYPTO                   /* CRYPTO STATISTICS                    */' }
        - { regexp: '^  IOQ\(DASD\)', line: '  IOQ(NODASD)                /* DASD I/O QUEUEING MEASURED           */' }

    - name: Configure VTAMALL for RMF start
      zos_blockinfile:
        src: "USER.{{ adcd_ver }}.PARMLIB(VTAMALL)"
        insertafter: "S TN3270"
        block: |
          S RMF,,,(SMFBUF(RECTYPE(70:78)))
          PAUSE 10
          F RMF,START AB
          F RMF,START III

    - name: Configure SHUTALL for RMF stop
      zos_lineinfile:
        src: "USER.{{ adcd_ver }}.PARMLIB(SHUTALL)"
        insertbefore: '^P TSO'
        line: 'P RMF'

    - name: Display configuration summary
      debug:
        msg: "RMF configuration completed: ERBRMF00, VTAMALL, and SHUTALL updated"