###############################################################################
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Example:
#  ansible-playbook -i inventories rmf_configuration.yml
#  ansible-playbook -i inventories rmf_configuration.yml -v
###############################################################################
---
- hosts: ben_s0w1 
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  vars:
    adcd_ver: Z25C

  environment: "{{ environment_vars }}"

  tasks:
    - name: Ping using zos_ping
      zos_ping:
      register: zos_ping_result

    - name: Response from zos_ping
      debug:
        msg: "{{ zos_ping_result }}"

###############################################################################
# Usage:
#  Copy SYS1.PARMLIB(ERBRMF00) to USER.{{ adcd_ver }}.PARMLIB(ERBRMF00)
###############################################################################

    - name: Copy ERBRMF00 from SYS1 to USER; replace if it already exists.
      zos_copy:
        src: SYS1.PARMLIB(ERBRMF00)
        dest: USER.{{ adcd_ver }}.PARMLIB(ERBRMF00)
        remote_src: true
      register: zos_copy_result

    - name: DEBUG(-v) Response from Copy VATLSTDB from ADCD to USER.
      debug:
        msg: "{{ zos_copy_result }} with verbosity 1"
        verbosity: 1

###############################################################################
# Usage:
#  Alter the following parameters in ERBRMF00 as they are not required for zPDT
#  NOCACHE
#  NOCHAN
#  NOCRYPTO
#  IOQ(NODASD) 
###############################################################################

    - name: Update ERBRMF00 to NOCACHE.
      zos_lineinfile:
        src: USER.{{ adcd_ver }}.PARMLIB(ERBRMF00)
        regexp: '^  CACHE'
        line: '  NOCACHE                    /* CACHE   STATISTICS                   */'
      register: zos_lineinfile_result

    - name: DEBUG(-v) Response from Update ERBRMF00 to NOCACHE.
      debug:
        msg: "{{ zos_lineinfile_result }} with verbosity 1"
        verbosity: 1

    - name: Update ERBRMF00 to NOCHAN.
      zos_lineinfile:
        src: USER.{{ adcd_ver }}.PARMLIB(ERBRMF00)
        regexp: '^  CHAN'
        line: '  NOCHAN                     /* CHANNEL STATISTICS                   */'
      register: zos_lineinfile_result

    - name: DEBUG(-v) Response from Update ERBRMF00 to NOCHAN.
      debug:
        msg: "{{ zos_lineinfile_result }} with verbosity 1"
        verbosity: 1

    - name: Update ERBRMF00 to NOCRYPTO.
      zos_lineinfile:
        src: USER.{{ adcd_ver }}.PARMLIB(ERBRMF00)
        regexp: '^  CRYPTO'
        line: '  NOCRYPTO                   /* CRYPTO STATISTICS                    */'
      register: zos_lineinfile_result

    - name: DEBUG(-v) Response from Update ERBRMF00 to NOCRYPTO.
      debug:
        msg: "{{ zos_lineinfile_result }} with verbosity 1"
        verbosity: 1

    - name: Update ERBRMF00 to IOQ(NODASD).
      zos_lineinfile:
        src: USER.{{ adcd_ver }}.PARMLIB(ERBRMF00)
        regexp: '^  IOQ(DASD)'
        line: '  IOQ(NODASD)                /* DASD I/O QUEUEING MEASURED           */'
      register: zos_lineinfile_result

    - name: DEBUG(-v) Response from Update ERBRMF00 to IOQ(NODASD).
      debug:
        msg: "{{ zos_lineinfile_result }} with verbosity 1"
        verbosity: 1

###############################################################################
# Usage:
#  Alter both start and stop parmameters for RMF
###############################################################################

    - name: Insert RMF I II and III start into VTAMALL.
      zos_blockinfile:
        src: USER.{{ adcd_ver }}.PARMLIB(VTAMALL)
        insertafter: "S TN3270"
        marker: "/* {mark} ANSIBLE MANAGED BLOCK */"
        block: |
          S RMF,,,(SMFBUF(RECTYPE(70:78)))
          PAUSE 10
          F RMF,START AB
          F RMF,START III
      register: zos_blockinfile_result
      
    - name: DEBUG(-v) Response from Insert RMF I II and III start into VTAMALL.
      debug:
        msg: "{{ zos_blockinfile_result }} with verbosity 1"
        verbosity: 1

    - name: Insert RMF stop into SHUTALL.
      zos_lineinfile:
        src: USER.{{ adcd_ver }}.PARMLIB(SHUTALL)
        insertbefore: '^P TN3270'
        line: 'P RMF'
      register: zos_lineinfile_result

    - name: Insert RMF stop into SHUTALL.
      debug:
        msg: "{{ zos_lineinfile_result }} with verbosity 1"
        verbosity: 1