################################################################################
# Playbook: SMP/E ZFS Setup
# Purpose: Creates and mounts SMP/E ZFS filesystem on z/OS
# Usage: ansible-playbook -i inventories/inventory.yml smpe_zfs_setup.yml
# Prerequisites: 
#   - IBM z/OS Core collection installed
#   - Valid z/OS credentials configured
#   - Appropriate permissions for ZFS operations
################################################################################
---
- name: SMP/E ZFS Setup
  hosts: z31c_s0w1
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"
  
  vars:
    zfs_name: SMPE.SMPNTS.ZFS
    mount_point: /u/smpe/smpnts
    primary_cylinders: 100
    secondary_cylinders: 50
    parmlib_dataset: USER.Z31C.PARMLIB(BPXPRMZZ)

  tasks:
    - name: Create ZFS dataset
      zos_data_set:
        name: "{{ zfs_name }}"
        type: zfs
        space_primary: "{{ primary_cylinders }}"
        space_secondary: "{{ secondary_cylinders }}"
        space_type: cyl
        state: present

    - name: Create mount point directory
      zos_mvs_raw:
        program: BPXBATCH
        parm: 'SH mkdir -p {{ mount_point }} && chmod 755 {{ mount_point }}'

    - name: Mount ZFS
      zos_mount:
        src: "{{ zfs_name }}"
        path: "{{ mount_point }}"
        fs_type: zfs
        state: mounted
        persistent:
          data_store: "{{ parmlib_dataset }}"