################################################################################
# Playbook: SMP/E ZFS Setup
# Purpose: Creates and mounts SMP/E ZFS filesystem on z/OS
# Usage: ansible-playbook -i <inventory_file> smpe_zfs.yml
################################################################################

---
- name: SMP/E ZFS Setup
  hosts: z31a_s0w1
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  vars:
    adcd_ver: Z31A
    zfs_name: SMPE.SMPNTS.ZFS
    mount_point: /u/smpe/smpnts
    primary_space: 100
    secondary_space: 50

  environment: "{{ environment_vars }}"

  tasks:
    - name: Verify connectivity
      zos_ping:

    - name: Unmount existing ZFS if present
      zos_mount:
        src: "{{ zfs_name }}"
        path: "{{ mount_point }}"
        fs_type: ZFS
        state: unmounted
      ignore_errors: true

    - name: Define SMPE catalog alias
      zos_tso_command:
        commands:
          - DEFINE ALIAS (NAME('SMPE') RELATE('USERCAT.{{ adcd_ver }}.USER'))
      ignore_errors: true

    - name: Create ZFS
      zos_data_set:
        name: "{{ zfs_name }}"
        type: zfs
        space_primary: "{{ primary_space }}"
        space_secondary: "{{ secondary_space }}"
        space_type: cyl
        replace: yes

    - name: Create mount point directory
      file:
        path: "{{ mount_point }}"
        state: directory

    - name: Mount ZFS
      zos_mount:
        src: "{{ zfs_name }}"
        path: "{{ mount_point }}"
        fs_type: ZFS
        state: mounted

    - name: Display setup summary
      debug:
        msg: "SMP/E ZFS setup completed: ZFS created and mounted at {{ mount_point }}"