###############################################################################
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Example:
#  ansible-playbook -i inventories smpe_zfs.yml
#  ansible-playbook -i inventories smpe_zfs.yml -v
###############################################################################
---
- hosts: ben_s0w1 
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  vars:
    adcd_ver: Z25C

  environment: "{{ environment_vars }}"

  tasks:
    - name: Ping using zos_ping
      zos_ping:
      register: zos_ping_result

    - name: Response from zos_ping
      debug:
        msg: "{{ zos_ping_result }}"

###############################################################################
# Usage:
#  UNMOUNT zfs SMPE.SMPNTS.ZFS
###############################################################################

    - name: Unmount zfs SMPE.SMPNTS.ZFS.
      zos_mount:
        src: SMPE.SMPNTS.ZFS
        path: /u/smpe/smpnts
        fs_type: ZFS
        state: unmounted
      ignore_errors: true
      register: zos_mount_result

    - name: DEBUG(-v) Response Unmount zfs SMPE.SMPNTS.ZFS.
      debug:
        msg: "{{ zos_mount_result }} with verbosity 1"
        verbosity: 1

###############################################################################
# Usage:
#  Define catalog ALIAS SMPE
###############################################################################

    - name: Define alias SMPE.
      zos_tso_command:
        commands:
          - DEFINE ALIAS (NAME('SMPE') RELATE('USERCAT.{{ adcd_ver }}.USER'))
      ignore_errors: true
      register: zos_tso_command_result

    - name: DEBUG(-v) Response from Define alias SMPE.
      debug:
        msg: "{{ zos_tso_command_result }} with verbosity 1"
        verbosity: 1

###############################################################################
# Usage:
#  Create zfs SMPE.SMPNTS.ZFS
#  Create directory /u/smpe/smpnts
###############################################################################

    - name: Create zfs SMPE.SMPNTS.ZFS.
      zos_data_set:
        name: SMPE.SMPNTS.ZFS
        type: zfs
        space_primary: 100
        space_secondary: 50
        space_type: cyl
        replace: yes
      register: zos_data_set_result

    - name: DEBUG(-v) Response Create zfs SMPE.SMPNTS.ZFS.
      debug:
        msg: "{{ zos_data_set_result }} with verbosity 1"
        verbosity: 1
 
    - name: Create smpnts directory for zfs mount.
      file:
        path: /u/smpe/smpnts
        state: directory
      register: file_result

    - name: Response from Create smpnts directory for zfs mount.
      debug:
        msg: "{{ file_result }}"

###############################################################################
# Usage:
#  MOUNT zfs SMPE.SMPNTS.ZFS to /u/smpe/smpnts
###############################################################################

    - name: Mount zfs SMPE.SMPNTS.ZFS.
      zos_mount:
        src: SMPE.SMPNTS.ZFS
        path: /u/smpe/smpnts
        fs_type: ZFS
        state: mounted
      register: zos_mount_result

    - name: DEBUG(-v) Response Mount zfs SMPE.SMPNTS.ZFS.
      debug:
        msg: "{{ zos_mount_result }} with verbosity 1"
        verbosity: 1