################################################################################
# Playbook: Setup of CICS EGUI environment
# Purpose: Implement EGUI
# Usage: ansible-playbook -i inventories/inventory.yml subsys_setup_cics_egui.yml
################################################################################
---
- name: CICS EGUI Setup
  hosts: z31a_s0w1
  collections:
    - ibm.ibm_zos_core
  gather_facts: yes
  vars:
    jcl_library: IBMUSER.GIT.JCL.CNTL
    wait_time_seconds: 120
    max_rc: 0
    cics_sip_dataset: DFH620.SYSIN(DFH$SIP1)
    dfltuser: IBMUSER
  environment: "{{ environment_vars }}"
  tasks:
    - name: Verify connectivity
      zos_ping:
      register: ping_result

    - name: Create and define VSAM data sets
      block:
        - name: Submit DFH$ECAT job
          zos_job_submit:
            src: "{{ jcl_library }}(DFH$ECAT)"
            location: DATA_SET
            wait_time_s: "{{ wait_time_seconds }}"
            max_rc: "{{ max_rc }}"
          register: ecat_result

        - name: Submit DFH$ECNF job
          zos_job_submit:
            src: "{{ jcl_library }}(DFH$ECNF)"
            location: DATA_SET
            wait_time_s: "{{ wait_time_seconds }}"
            max_rc: "{{ max_rc }}"
          register: ecnf_result

    - name: Submit CICS system definition for zOffice
      zos_job_submit:
        src: "{{ jcl_library }}(CICSCSD)"
        location: DATA_SET
        wait_time_s: "{{ wait_time_seconds }}"
        max_rc: "{{ max_rc }}"
      register: cicscsd_result

    - name: Update DFLTUSER in CICS SIP
      zos_lineinfile:
        src: "{{ cics_sip_dataset }}"
        regexp: '^DFLTUSER=CICSUSER'
        line: 'DFLTUSER={{ dfltuser }}                          ANSIBLE UPDATED {{ ansible_date_time.iso8601 }}'
      register: sip_result

    - name: Display detailed execution summary
      debug:
        msg: |
          CICS EGUI Setup Summary
          ==============================
          Timestamp: {{ ansible_date_time.iso8601 }}
          Host: {{ inventory_hostname }}
          
          Execution Status:
          - Overall Status: {{ update_result.failed | default(false) | ternary('Failed', 'Success') }}
          - Changes Made: {{ (ecat_result.changed or ecnf_result.changed or cicscsd_result.changed or sip_result.changed) | ternary('Yes', 'No') }}
          
          Verification Results:
          - Connectivity Check: {{ ping_result.failed | default(false) | ternary('Failed', 'Success') }}
          - VSAM Setup:
            * DFH$ECAT Job: {{ ecat_result.failed | default(false) | ternary('Failed', 'Success') }}
            * DFH$ECNF Job: {{ ecnf_result.failed | default(false) | ternary('Failed', 'Success') }}
          - CICS Configuration:
            * System Definition: {{ cicscsd_result.failed | default(false) | ternary('Failed', 'Success') }}
            * SIP Update: {{ sip_result.changed | ternary('Updated DFLTUSER to ' + dfltuser, 'No change needed') }}
          
          Configuration Details:
          - JCL Library: {{ jcl_library }}
          - SIP Dataset: {{ cics_sip_dataset }}
          - Default User: {{ dfltuser }}
      when: true