###############################################################################
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Example:
#  ansible-playbook -i inventory base_auto_mount.yml
#  ansible-playbook -i inventory base_auto_mount.yml -v
###############################################################################
---
- hosts: ben_s0w1 
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  vars:
    adcd_ver: Z25A

  environment: "{{ environment_vars }}"

  tasks:
    - name: Ping using zos_ping
      zos_ping:
      register: zos_ping_result

    - name: Response from zos_ping
      debug:
        msg: "{{ zos_ping_result }}"

###############################################################################
# Usage:
#  Create empty file /etc/auto.master 
#  /u directory is to be configured, along with the MapName file.
###############################################################################

    - name: text file test
      shell: |
         echo "/u                /etc/u.map" > /tmp/auto.master
      register: zos_shell

    - name: DEBUG(-v) Response from Add directory and MapName file.
      debug:
        msg: "{{ zos_shell }} with verbosity 1"
        verbosity: 1

###############################################################################
# Usage:
#   Create empty file /etc/u.map
#   ZFS attributes related to /u directory  
###############################################################################

    - name: text file test
      shell: |
         echo "cat > /tmp/u.map << EOF
               name                             *
               type                             ZFS
               filesystem                       <uc_name>.&SYSNAME..ZFS
               mode                             rdwr
               duration                         30
               delay                            10
               allocany space(1,1) cyl unit(disk) pathperm(775) euid ucat/u
               EOF"             
      register: zos_shell