################################################################################
# Playbook: MQ Parameter Update
# Purpose: Updates MQ parameters and manages queue manager CSQ9
# Usage: ansible-playbook -i <inventory_file> update_mq.yml
################################################################################

---
- name: MQ Parameter Update
  hosts: ben_s0w1
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  vars:
    mq_CSQ4ZPRM: CSQ920.SVSC.CUSTOM.INSTALL(CSQ4ZPRM)
    mq_CSQ4INYG: CSQ920.CSQ9.SCSQPROC(CSQ4INYG)
    qmgr_name: CSQ9
    job_wait_time: 120

  environment: "{{ environment_vars }}"

  tasks:
    - name: Verify connectivity
      zos_ping:

    - name: Update CSQ4ZPRM SMF parameters
      zos_lineinfile:
        src: "{{ mq_CSQ4ZPRM }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^               SMFACCT=NO,', line: '               SMFACCT=YES,          GATHER SMF ACCOUNTING             X' }
        - { regexp: '^               SMFSTAT=NO,', line: '               SMFSTAT=YES,          GATHER SMF STATS                  X' }

    - name: Stop MQ Queue Manager
      zos_operator:
        cmd: "%{{ qmgr_name }} STOP QMGR"

    - name: Submit CSQ4ZPRM job
      zos_job_submit:
        src: "{{ mq_CSQ4ZPRM }}"
        location: DATA_SET
        wait: true
        wait_time_s: "{{ job_wait_time }}"

    - name: Update CSQ4INYG PSMODE parameter
      zos_lineinfile:
        src: "{{ mq_CSQ4INYG }}"
        regexp: '^         PSMODE'
        line: '         PSMODE( ENABLED ) +'

    - name: Start MQ Queue Manager
      zos_operator:
        cmd: "%{{ qmgr_name }} START QMGR"

    - name: Start MQ Channel Initiator
      zos_operator:
        cmd: "%{{ qmgr_name }} START CHINIT"

    - name: Display completion message
      debug:
        msg: "MQ parameter update completed: SMF and PSMODE parameters updated, queue manager restarted"