###############################################################################
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Example:
#  ansible-playbook -i inventory z25a_housekeeping.yml
#  ansible-playbook -i inventory z25a_housekeeping.yml -v
###############################################################################
---
- hosts: ben_s0w1 
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  vars:
    adcd_ver: Z24C
    cntl_hlq: IBMUSER.GIT.JCL.CNTL

  environment: "{{ environment_vars }}"

  tasks:
    - name: Ping using zos_ping
      zos_ping:
      register: zos_ping_result

    - name: Response from zos_ping
      debug:
        msg: "{{ zos_ping_result }}"

###############################################################################
# Usage:
#  Submit LOGREC and wait for the job to finish
###############################################################################

    - name: Submit LOGREC and wait for the job to finish.
      zos_job_submit:
        src: "{{ cntl_hlq }}(LOGREC)"
        location: DATA_SET
        wait: true
        wait_time_s: 30
      register: zos_job_submit_result

    - name: DEBUG(-v) Response Submit LOGREC and wait for the job to finish.
      debug:
        msg: "{{ zos_job_submit_result }} with verbosity 1"
        verbosity: 1

###############################################################################
# Usage:
#  Submit DSSDFRAG and wait for the job to finish
###############################################################################

    - name: Submit DSSDFRAG and wait for the job to finish.
      zos_job_submit:
        src: "{{ cntl_hlq }}(DSSDFRAG)"
        location: DATA_SET
        wait: true
        wait_time_s: 120
      register: zos_job_submit_result

    - name: DEBUG(-v) Response Submit DSSDFRAG and wait for the job to finish.
      debug:
        msg: "{{ zos_job_submit_result }} with verbosity 1"
        verbosity: 1

###############################################################################
# Usage:
#  Submit DCOLLECT and wait for the job to finish zCDP
###############################################################################

    - name: Submit DCOLLECT and wait for the job to finish.
      zos_job_submit:
        src: "{{ cntl_hlq }}(DCOLLECT)"
        location: DATA_SET
        wait: true
        wait_time_s: 120
      register: zos_job_submit_result

    - name: DEBUG(-v) Response Submit DCOLLECT and wait for the job to finish.
      debug:
        msg: "{{ zos_job_submit_result }} with verbosity 1"
        verbosity: 1

###############################################################################
# Usage:
#  Submit HBOJBDC2 and wait for the job to finish ZCDP
###############################################################################

    - name: Submit HBOJBDC2 and wait for the job to finish.
      zos_job_submit:
        src: "{{ cntl_hlq }}(HBOJBDC2)"
        location: DATA_SET
        wait: true
        wait_time_s: 120
      register: zos_job_submit_result

    - name: DEBUG(-v) Response Submit HBOJBDC2 and wait for the job to finish.
      debug:
        msg: "{{ zos_job_submit_result }} with verbosity 1"
        verbosity: 1

###############################################################################
# Usage:
#  JES2 Purge output data sets are more than 21 days
###############################################################################

    - name: Execute JES2 Purge waiting 10 seconds for response.
      zos_operator:
        cmd: "$P O JQ,ALL,A>21"
        wait_time_s: 10
        wait: true
      register: zos_operator_result

    - name: DEBUG(-v) Response Execute JES2 Purge waiting 10 seconds for response.
      debug:
        msg: "{{ zos_operator_result }} with verbosity 1"
        verbosity: 1

###############################################################################
# Usage:
#  Delete zWIC files older than than 5 days
###############################################################################

    - name: Delete zWIC files older than 5 days.
      shell: "find /global/wic/S0W1 -type f -mtime +5 -exec rm {} \;"
      register: shell_result

    - name: DEBUG(-v) Response Delete zWIC files older than 5 days.
      debug:
        msg: "{{ shell_result }} with verbosity 1"
        verbosity: 1
