################################################################################
# Playbook: z/OS PROCLIB Setup
# Purpose: Configures VTAMALL, SHUTALL, and DBSPROCD procedures
# Usage: ansible-playbook -i <inventory_file> proclib_setup.yml
################################################################################

---
- name: z/OS PROCLIB Setup
  hosts: z31a_s0w1
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  vars:
    adcd_ver: Z31A

  environment: "{{ environment_vars }}"

  tasks:
    - name: Verify connectivity
      zos_ping:

    - name: Copy PROCLIB members
      zos_copy:
        src: "ADCD.{{ adcd_ver }}.PROCLIB({{ item }})"
        dest: "USER.{{ adcd_ver }}.PROCLIB({{ item }})"
        remote_src: true
      loop:
        - VTAMALL
        - SHUTALL
        - DBSPROCD

    - name: Update PARMLIB DD statements
      zos_lineinfile:
        src: "USER.{{ adcd_ver }}.PROCLIB({{ item }})"
        regexp: '^//PARMLIB'
        line: '//PARMLIB  DD  DSN=USER.&SYSVER..PARMLIB(&M),DISP=SHR'
      loop:
        - VTAMALL
        - SHUTALL

    - name: Display completion message
      debug:
        msg: "PROCLIB setup completed: VTAMALL, SHUTALL, and DBSPROCD configured"