################################################################################
# Playbook: Dataset Commander Setup
# Purpose: Updates DBSPROCD procedure with Dataset Commander libraries
# Usage: ansible-playbook -i inventories/inventory.yml zos_dataset_commander_customization.yml
################################################################################

---
- name: Dataset Commander Customization
  hosts: z31a_s0w1
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  vars:
    adcd_ver: Z31A
    dsc_version: IQI910
    dbsprocd_dataset: "USER.{{ adcd_ver }}.PROCLIB(DBSPROCD)"

  environment: "{{ environment_vars }}"

  tasks:
    - name: Verify connectivity
      zos_ping:

    - name: Add Dataset Commander DD statements
      zos_lineinfile:
        src: "{{ dbsprocd_dataset }}"
        insertafter: "{{ item.insertafter }}"
        insertbefore: "{{ item.insertbefore | default(omit) }}"
        line: "{{ item.line }}"
      loop:
        - { insertbefore: '^//SYSUADS', line: '//STEPLIB  DD  DISP=SHR,DSN={{ dsc_version }}.SIQILPA' }
        - { insertafter: '^//STEPLIB', line: '//         DD  DISP=SHR,DSN={{ dsc_version }}.SIQILOAD' }
        - { insertafter: '^//ISPLLIB', line: '//         DD  DISP=SHR,DSN={{ dsc_version }}.SIQILOAD' }
        - { insertafter: '^//ISPLLIB', line: '//         DD  DISP=SHR,DSN={{ dsc_version }}.SIQILPA' }
        - { insertafter: '^//SYSPROC', line: '//         DD  DISP=SHR,DSN={{ dsc_version }}.SIQICLIB' }
        - { insertafter: '^//ISPMLIB', line: '//         DD  DISP=SHR,DSN={{ dsc_version }}.SIQIMLIB' }
        - { insertafter: '^//ISPPLIB', line: '//         DD  DISP=SHR,DSN={{ dsc_version }}.SIQIPLIB' }
        - { insertafter: '^//ISPSLIB', line: '//         DD  DISP=SHR,DSN={{ dsc_version }}.SIQISLIB' }
        - { insertafter: '^//SDSFMENU', line: '//IQITLIB  DD  DISP=SHR,DSN={{ dsc_version }}.SIQITLIB' }
        - { insertafter: '^//IQITLIB', line: '//IQIUT04  DD  DISP=NEW,UNIT=VIO,SPACE=(3,1)' }
        - { insertafter: '^//IQITLIB', line: '//IQIUT03  DD  DISP=NEW,UNIT=VIO,SPACE=(3,1)' }
        - { insertafter: '^//IQITLIB', line: '//IQIUTOT  DD  DISP=NEW,UNIT=SYSALLDA,' }
        - { insertafter: '^//IQIUTOT', line: '//         SPACE=(CYL,(2,2)),RECFM=FBA,LRECL=121,BLKSIZE=4840' }
        - { insertafter: '^//IQITLIB', line: '//IQIUTIN  DD  DISP=NEW,UNIT=VIO,' }
        - { insertafter: '^//IQIUTIN', line: '//         SPACE=(CYL,(1,1)),RECFM=FB,LRECL=80,BLKSIZE=4000' }

    - name: Display completion message
      debug:
        msg: "Dataset Commander customization completed: DBSPROCD updated with required DD statements"