################################################################################
# Playbook Name: JZOS Setup
# Purpose:
#   - Sets up the JZOS Batch Launcher and Toolkit on z/OS systems.
#   - Copies necessary JCL and PROC files to appropriate datasets.
#
# Requirements:
#   - Ansible 2.9 or higher
#   - Access to z/OS system with appropriate permissions
#   - IBM z/OS Core Collection installed
#
# Usage:
#   - Basic execution: ansible-playbook -i inventories zos_jzos_setup.yml
#   - With verbosity: ansible-playbook -i inventories zos_jzos_setup.yml -v
################################################################################
---
- hosts: z31a_s0w1
  gather_facts: yes
  collections:
    - ibm.ibm_zos_core

  environment: "{{ environment_vars }}"
  
  tasks:
    - name: Copy JVMJCL17 to SYS1.SAMPLIB
      zos_copy:
        src: /usr/lpp/java/J17.0_64/mvstools/jcl/JVMJCL17
        dest: SYS1.SAMPLIB(JVMJCL17)
        remote_src: true

    - name: Copy JVMPRC17 to SYS1.PROCLIB
      zos_copy:
        src: /usr/lpp/java/J17.0_64/mvstools/jcl/JVMPRC17
        dest: SYS1.PROCLIB(JVMPRC17)
        remote_src: true

    - name: Copy JVMLDM17 to SYS1.SIEALNKE 
      zos_copy:
        src: /usr/lpp/java/J17.0_64/mvstools/JVMLDM17
        dest: SYS1.SIEALNKE(JVMLDM17)
        is_binary: true
        remote_src: true