################################################################################
# Playbook: z/OS Housekeeping
# Purpose: Runs system maintenance tasks (LOGREC, DCOLLECT, SMF, cleanup)
# Usage: ansible-playbook -i <inventory_file> housekeeping.yml
################################################################################

---
- name: z/OS Housekeeping
  hosts: z31a_s0w1
  gather_facts: yes
  collections:
    - ibm.ibm_zos_core

  vars:
    cntl_hlq: IBMUSER.GIT.JCL.CNTL
    wait_time_s: 120
    max_rc_logrec: 0
    max_rc_dcollect: 4
    max_rc_smf: 4
    temp_files_directory: /tmp
    temp_file_age: 20d
    jes2_output_age: 21
    dump_pattern: "SYS1.S0W1.Z31A.DMP*"
    dump_age: 1w
    zwicdata_dir: /global/zwicdata/
    zwicdata_age: 5d

  environment: "{{ environment_vars }}"

  tasks:
    - name: Verify connectivity
      zos_ping:

    - name: Submit and monitor jobs
      zos_job_submit:
        src: "{{ cntl_hlq }}({{ item.job }})"
        location: data_set
        wait_time_s: "{{ wait_time_s }}"
        max_rc: "{{ item.max_rc }}"
      loop:
        - { job: 'LOGREC', max_rc: "{{ max_rc_logrec }}" }
        - { job: 'DCOLLECT', max_rc: "{{ max_rc_dcollect }}" }
        - { job: 'IFASMFDL', max_rc: "{{ max_rc_smf }}" }
      ignore_errors: yes

    - name: Purge old JES2 output
      zos_operator:
        cmd: "\\$P O JQ,ALL,A>{{ jes2_output_age }}"
      ignore_errors: yes

    - name: Clean up temp files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ lookup('find', temp_files_directory, age=temp_file_age, recurse=True) }}"
      ignore_errors: yes

    - name: Clean up old dumps
      zos_data_set:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ lookup('zos_find', patterns=[dump_pattern], age=dump_age) }}"
      ignore_errors: yes

    - name: Clean up zwicdata files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ lookup('find', zwicdata_dir, age=zwicdata_age, recurse=True) }}"
      ignore_errors: yes

    - name: Display summary
      debug:
        msg: "Housekeeping tasks completed: LOGREC/DCOLLECT/SMF jobs run, old files cleaned up"