################################################################################
# Playbook Name: Enhanced z/OS Ping
#
# Purpose:
#   This playbook performs a ping operation on a z/OS system using the zos_ping
#   module from the IBM z/OS Core Collection. It demonstrates various ways to
#   display debug information based on verbosity levels and boolean flags.
#
# Requirements:
#   - Ansible 2.9 or higher
#   - IBM z/OS Core Collection (ibm.ibm_zos_core) installed
#   - Access to z/OS system with appropriate permissions
#   - Proper setup of Ansible inventory file with z/OS target information
#
# Usage:
#   Basic execution:
#     ansible-playbook -i <inventory_file> zos_ping.yml
#
#   With increased verbosity:
#     ansible-playbook -i <inventory_file> zos_ping.yml -v
#     ansible-playbook -i <inventory_file> zos_ping.yml -vv
#
#   With boolean debug flag:
#     ansible-playbook -i <inventory_file> zos_ping.yml -e "boolean_debug=true"
#
#   With enable_debug flag:
#     ansible-playbook -i <inventory_file> zos_ping.yml -e "enable_debug=yes"
#
# Variables:
#   boolean_debug: Boolean flag to enable additional debugging (default: false)
#   enable_debug: String flag to enable additional debugging (default: "no")
#
# Notes:
#   - This playbook uses the zos_ping module which requires the zos_ssh connection.
#   - Debug messages are displayed based on verbosity levels and debug flags.
#   - The playbook demonstrates different ways to control debug output.
#
# Examples:
#   1. Run the playbook with default settings:
#      ansible-playbook -i inventories/inventory.yml zos_ping.yml
#
#   2. Run the playbook with verbose output:
#      ansible-playbook -i inventories/inventory.yml zos_ping.yml -v
#
#   3. Run the playbook with boolean debug enabled:
#      ansible-playbook -i inventories/inventory.yml zos_ping.yml -e "boolean_debug=true"
#
#   4. Run the playbook with enable_debug set to yes:
#      ansible-playbook -i inventories/inventory.yml zos_ping.yml -e "enable_debug=yes"
#
################################################################################

---
- name: Enhanced z/OS Ping
  hosts: z31a_s0w1
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  vars:
    boolean_debug: false
    enable_debug: "no"

  tasks:
    - name: Perform z/OS ping
      zos_ping:
      register: zos_ping_result

    - name: Display basic ping response
      debug:
        msg: "Ping result: {{ zos_ping_result.ping }}"

    - name: Display detailed ping response (verbosity 1)
      debug:
        msg: "Detailed ping result: {{ zos_ping_result }}"
        verbosity: 1

    - name: Display extra debug info (verbosity 2)
      debug:
        msg: "Extra debug info: {{ zos_ping_result | to_nice_json }}"
        verbosity: 2

    - name: Display debug info (boolean flag)
      debug:
        msg: "Debug info (boolean flag): {{ zos_ping_result }}"
      when: boolean_debug | bool

    - name: Display debug info (enable_debug flag)
      debug:
        msg: "Debug info (enable_debug flag): {{ zos_ping_result }}"
      when: enable_debug == "yes"

    - name: Display summary
      debug:
        msg:
          - "z/OS Ping Summary:"
          - "- Ping status: {{ 'Successful' if zos_ping_result.ping == 'pong' else 'Failed' }}"
          - "- Host: {{ inventory_hostname }}"
          - "- Module: {{ zos_ping_result.invocation.module_name }}"
          - "- Boolean debug: {{ boolean_debug }}"
          - "- Enable debug: {{ enable_debug }}"

    - name: Check ping result
      assert:
        that:
          - zos_ping_result.ping == "pong"
        fail_msg: "z/OS ping failed. Please check your connection and permissions."
        success_msg: "z/OS ping successful."
