################################################################################
# Playbook: z/OS Housekeeping
# Purpose: Runs system maintenance tasks (LOGREC, DCOLLECT, SMF, cleanup)
# Usage: ansible-playbook -i inventories/inventory.yml zos_housekeeping.yml
################################################################################

---
- name: z/OS Housekeeping
  hosts: z31a_s0w1
  gather_facts: yes
  collections:
    - ibm.ibm_zos_core

  vars:
    cntl_hlq: IBMUSER.GIT.JCL.CNTL
    wait_time_s: 120
    max_rc_logrec: 0
    max_rc_dcollect: 4
    max_rc_smf: 4
    temp_files_directory: /tmp
    temp_file_age: 20d
    jes2_output_age: 21
    dump_pattern: "SYS1.S0W1.Z31A.DMP*"
    dump_age: 1w
    zwicdata_dir: /global/zwicdata/
    zwicdata_age: 5d
    skip_temp_cleanup: false

  environment: "{{ environment_vars }}"

  tasks:
    - name: Verify connectivity
      zos_ping:

    - name: Submit and monitor jobs
      zos_job_submit:
        src: "{{ cntl_hlq }}({{ item.job }})"
        location: data_set
        wait_time_s: "{{ wait_time_s }}"
        max_rc: "{{ item.max_rc }}"
      loop:
        - { job: 'LOGREC', max_rc: "{{ max_rc_logrec }}" }
        - { job: 'DCOLLECT', max_rc: "{{ max_rc_dcollect }}" }
        - { job: 'IFASMFDL', max_rc: "{{ max_rc_smf }}" }
      register: job_results

    - name: Purge old JES2 output
      zos_operator:
        cmd: "\\$P O JQ,ALL,A>{{ jes2_output_age }}"
      register: jes2_purge

    - name: Manage temporary files
      block:
        - name: Find tmp files older than {{ temp_file_age }}
          find:
            paths: "{{ temp_files_directory }}"
            age: "{{ temp_file_age }}"
            recurse: yes
          register: tmp_files_to_delete

        - name: Delete old tmp files
          file:
            path: "{{ item.path }}"
            state: absent
          loop: "{{ tmp_files_to_delete.files }}"
          when: tmp_files_to_delete.matched > 0
      when: not skip_temp_cleanup
      ignore_errors: yes

    - name: Manage dump datasets
      block:
        - name: Find old dumps
          zos_find:
            patterns:
              - "{{ dump_pattern }}"
            age: "{{ dump_age }}"
          register: dump_results

        - name: Delete old dumps
          zos_data_set:
            name: "{{ item }}"
            state: absent
          loop: "{{ dump_results.data_sets | default([]) }}"
          when: dump_results.data_sets is defined and dump_results.data_sets | length > 0
      ignore_errors: yes

    - name: Manage zwicdata files
      block:
        - name: Find old zwicdata files
          find:
            paths: "{{ zwicdata_dir }}"
            age: "{{ zwicdata_age }}"
            recurse: yes
          register: zwicdata_files_to_delete

        - name: Delete old zwicdata files
          file:
            path: "{{ item.path }}"
            state: absent
          loop: "{{ zwicdata_files_to_delete.files }}"
          when: zwicdata_files_to_delete.matched > 0
      ignore_errors: yes

    - name: Display summary
      debug:
        msg: |
          Housekeeping tasks completed:
          - Job submissions: {{ 'Success' if job_results is success else 'Failed' }}
          - JES2 purge: {{ 'Success' if jes2_purge is success else 'Failed' }}
          - Temp files found: {{ tmp_files_to_delete.matched | default(0) }}
          - Dumps found: {{ (dump_results.data_sets | default([])) | length }}
          - Zwicdata files found: {{ zwicdata_files_to_delete.matched | default(0) }}