################################################################################
# Playbook: z/OS System Configuration
# Purpose: Configures system parameters and PARMLIB members
# Usage: ansible-playbook -i <inventory_file> zos_config.yml
################################################################################

---
- name: z/OS System Configuration
  hosts: z31a_s0w1
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  vars:
    adcd_ver: Z31A

  environment: "{{ environment_vars }}"

  tasks:
    - name: Verify connectivity
      zos_ping:

    - name: Configure CLOCK00
      zos_copy:
        src: "ADCD.{{ adcd_ver }}.PARMLIB(CLOCK00)"
        dest: "USER.{{ adcd_ver }}.PARMLIB(CLOCK00)"
        remote_src: true

    - name: Set timezone
      zos_lineinfile:
        src: "USER.{{ adcd_ver }}.PARMLIB(CLOCK00)"
        regexp: '^TIMEZONE'
        line: 'TIMEZONE E.10.00.00'

    - name: Configure BPXPRMZZ
      zos_blockinfile:
        src: "USER.{{ adcd_ver }}.PARMLIB(BPXPRMZZ)"
        marker: "/* {mark} ANSIBLE MANAGED BLOCK */"
        create: yes
        block: |
          /* IBM Python V3.10 */
          MOUNT FILESYSTEM('CYP3B0.ZFS')
                TYPE(ZFS) MODE(READ) NOAUTOMOVE
                MOUNTPOINT('/usr/lpp/IBM/cyp/v3r11')
          /* IBM Python V3.9 */
          MOUNT FILESYSTEM('CYP390.ZFS')
                TYPE(ZFS) MODE(READ) NOAUTOMOVE
                MOUNTPOINT('/usr/lpp/IBM/cyp/v3r9')
          /* SMPE ZFS */ 
          MOUNT FILESYSTEM('SMPE.SMPNTS.ZFS')
                TYPE(ZFS) MODE(RDWR) NOAUTOMOVE
                MOUNTPOINT('/u/smpe/smpnts')

    - name: Update system parameters
      zos_lineinfile:
        src: "USER.{{ adcd_ver }}.PARMLIB({{ item.member }})"
        regexp: "{{ item.regexp | default(omit) }}"
        line: "{{ item.line }}"
        insertafter: "{{ item.after | default(omit) }}"
        insertbefore: "{{ item.before | default(omit) }}"
      loop:
        - { member: 'IEASYSAL', regexp: '^OMVS=', line: 'OMVS=(00,01,BP,IZ,CI,DB,IM,W9,RZ,RT,BB,ZW,ZZ), BPXPARMZZ ANSIBLE MANAGED' }
        - { member: 'IEASYSAL', after: '^VIODSN=', line: 'LFAREA=(1M=(25%,0%),NOPROMPT), Z/OS LARGE FRAME SUPPORT' }
        - { member: 'IEASYSAL', after: '^ILMMODE', line: 'IKJTSO=ZZ,' }
        - { member: 'VTAMALL', after: '^S ZOSCSRV', line: 'S FTPD' }
        - { member: 'SHUTALL', before: '^P RSED', line: 'P FTPD' }

    - name: Copy PARMLIB members
      zos_copy:
        src: "ADCD.{{ adcd_ver }}.PARMLIB({{ item }})"
        dest: "USER.{{ adcd_ver }}.PARMLIB({{ item }})"
        remote_src: true
      loop:
        - IKJTSO00
        - IEFSSNDB
        - IEASYM00
        - IZUPRMAS

    - name: Display completion message
      debug:
        msg: "System configuration completed: PARMLIB members updated and configured"