################################################################################
# Playbook: JZOS Setup
# Purpose: Sets up JZOS Batch Launcher by copying required components
# Usage: ansible-playbook -i inventories/inventory.yml zos_jzos_setup.yml
################################################################################

---
- name: JZOS Setup
  hosts: z31a_s0w1
  gather_facts: yes
  collections:
    - ibm.ibm_zos_core

  vars:
    java_version: J17.0_64
    java_home: /usr/lpp/java
    samplib_dataset: SYS1.SAMPLIB
    proclib_dataset: SYS1.PROCLIB
    siealnke_dataset: SYS1.SIEALNKE

  environment: "{{ environment_vars }}"

  tasks:
    - name: Verify connectivity
      zos_ping:

    - name: Copy JVMJCL17 to SAMPLIB
      zos_copy:
        src: "{{ java_home }}/{{ java_version }}/mvstools/jcl/JVMJCL17"
        dest: "{{ samplib_dataset }}(JVMJCL17)"
        remote_src: true

    - name: Copy JVMPRC17 to PROCLIB
      zos_copy:
        src: "{{ java_home }}/{{ java_version }}/mvstools/jcl/JVMPRC17"
        dest: "{{ proclib_dataset }}(JVMPRC17)"
        remote_src: true

    - name: Copy JVMLDM17 to SIEALNKE
      zos_copy:
        src: "{{ java_home }}/{{ java_version }}/mvstools/JVMLDM17"
        dest: "{{ siealnke_dataset }}(JVMLDM17)"
        is_binary: true
        remote_src: true

    - name: Display setup summary
      debug:
        msg: "JZOS setup completed: Components copied to SAMPLIB, PROCLIB, and SIEALNKE"