################################################################################
# Playbook: z/OS Housekeeping
# Purpose: Runs system maintenance tasks (LOGREC, DCOLLECT, SMF, cleanup)
# Usage: ansible-playbook -i inventories/inventory.yml zos_housekeeping.yml
################################################################################

---
- name: z/OS Housekeeping
  hosts: z31a_s0w1
  gather_facts: yes
  collections:
    - ibm.ibm_zos_core

  vars:
    cntl_hlq: IBMUSER.GIT.JCL.CNTL
    wait_time_s: 120
    max_rc_logrec: 0
    max_rc_dcollect: 4
    max_rc_smf: 4
    temp_files_directory: /tmp
    temp_file_age: 20d
    jes2_output_age: 21
    dump_pattern: "SYS1.S0W1.Z31A.DMP*"
    dump_age: 1w
    zwicdata_dir: /global/zwicdata/
    zwicdata_age: 5d

  environment: "{{ environment_vars }}"

  tasks:
    - name: Verify connectivity
      zos_ping:

    - name: Submit and monitor jobs
      zos_job_submit:
        src: "{{ cntl_hlq }}({{ item.job }})"
        location: data_set
        wait_time_s: "{{ wait_time_s }}"
        max_rc: "{{ item.max_rc }}"
      loop:
        - { job: 'LOGREC', max_rc: "{{ max_rc_logrec }}" }
        - { job: 'DCOLLECT', max_rc: "{{ max_rc_dcollect }}" }
        - { job: 'IFASMFDL', max_rc: "{{ max_rc_smf }}" }
      register: job_results

    - name: Purge old JES2 output
      zos_operator:
        cmd: "\\$P O JQ,ALL,A>{{ jes2_output_age }}"
      register: jes2_purge

    - name: Clean up temp files using shell command
      zos_shell:
        cmd: "find {{ temp_files_directory }} -type f -mtime +{{ temp_file_age | regex_replace('d$','') }} -delete"
      register: temp_cleanup
      
    - name: Find old dumps
      zos_find:
        patterns:
          - "{{ dump_pattern }}"
        age: "{{ dump_age }}"
      register: dump_files

    - name: Delete old dumps
      zos_data_set:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ dump_files.files }}"
      when: dump_files.files | length > 0
      register: dumps_deleted

    - name: Clean up zwicdata files using shell command
      zos_shell:
        cmd: "find {{ zwicdata_dir }} -type f -mtime +{{ zwicdata_age | regex_replace('d$','') }} -delete"
      register: zwicdata_cleanup

    - name: Display summary
      debug:
        msg: |
          Housekeeping tasks completed:
          - Job submissions: {{ 'Success' if job_results is success else 'Failed' }}
          - JES2 purge: {{ 'Success' if jes2_purge is success else 'Failed' }}
          - Temp cleanup: {{ 'Success' if temp_cleanup is success else 'Failed' }}
          - Dumps cleaned: {{ dump_files.files | length }} dumps found and processed
          - Zwicdata cleanup: {{ 'Success' if zwicdata_cleanup is success else 'Failed' }}