################################################################################
# Playbook: z/OS Automount Setup
# Purpose: Configures USS Automount facility and related files
# Usage: ansible-playbook -i <inventory_file> zos_automount.yml
################################################################################

---
- name: z/OS Automount Setup
  hosts: z31a_s0w1
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  vars:
    adcd_ver: Z31A
    rc_backup_path: /tmp/rc-backup
    auto_master_path: /etc/auto.master
    u_map_path: /etc/u.map

  environment: "{{ environment_vars }}"

  tasks:
    - name: Verify connectivity
      zos_ping:

    - name: Backup /etc/rc file
      zos_copy:
        src: /etc/rc
        dest: "{{ rc_backup_path }}"
        remote_src: true

    - name: Configure automount in /etc/rc
      zos_blockinfile:
        path: /etc/rc
        insertafter: "chmod 1755 /dev"
        block: |
          # Start the automount facility
          /usr/sbin/automount

    - name: Create /etc/auto.master
      copy:
        content: "/u/automount      {{ u_map_path }}"
        dest: "{{ auto_master_path }}"

    - name: Create /etc/u.map
      copy:
        content: |
          name                             *
          type                             ZFS
          filesystem                       OMVS.<uc_name>.&SYSNAME..ZFS
          mode                             rdwr
          duration                         30
          delay                            10
          allocany space(1,1) cyl unit(disk) pathperm(775) euid ucat
        dest: "{{ u_map_path }}"

    - name: Define OMVS catalog alias
      zos_tso_command:
        commands:
          - DEFINE ALIAS (NAME('OMVS') RELATE('USERCAT.{{ adcd_ver }}.USER'))
      ignore_errors: true

    - name: Display setup completion
      debug:
        msg: "Automount setup completed: /etc/rc updated, auto.master and u.map created"