---
ZOAU: "/Z31C/usr/lpp/IBM/zoautil"
PYZ: "/Z31C/usr/lpp/IBM/cyp/v3r12/pyz"
ansible_python_interpreter: "{{ PYZ }}/bin/python3.12"
environment_vars:
  "_BPXK_AUTOCVT": "ON"
  "ZOAU_HOME": "{{ ZOAU }}"
  "PYTHONPATH": "{{ ZOAU }}:/lib/3.12"
  "LIBPATH": "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  "PATH": "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin"
  "_CEE_RUNOPTS": "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  "_TAG_REDIR_ERR": "txt"
  "_TAG_REDIR_IN": "txt"
  "_TAG_REDIR_OUT": "txt"
  "LANG": "C"
  "PYTHONSTDINENCODING": "cp1047"